<section class="products_heading">Or Choose From Our Most Popular Apple Certified Repairs</section>
                        <section id="wn">
      <section id="lyr1">
      <ul>
      <li><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="195" height="269"></li>
      <li><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="195" height="269"></li>
      <li><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="195" height="269"></li>
      <li><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="195" height="269"></li>
      <li><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="195" height="269"></li>
      <li><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="195" height="269"></li>
      <li><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="195" height="269"></li>
      <li><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="195" height="269"></li>
      <li><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="195" height="269"></li>
      <li><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="195" height="269"></li>
      <li><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="195" height="269"></li>
     </ul>
        </section></section>
<section id="scrollLinks"></section>