<script type="text/javascript" src="<?php echo $this->getSkinUrl('close-div/jquery.min.js')?>"></script>

<script type="text/javascript">

 function showonlyone(thechosenone) {

     $('.newboxes').each(function(index) {

          if ($(this).attr("id") == thechosenone) {

               $(this).show(200);

          }

          else {

               $(this).hide(200);

          }

     });

}

</script>
<div class="list" style=" float:left;">

     <table width="100%" height="">

<tr>

 

<td style="vertical-align:top; float:left;">



 

         <div style=" margin:0px; padding:0px; padding-right:20px;   float:left; ">

            <a id="myHeader1" href="javascript:showonlyone('newboxes1');" >

			

				<img src="<?php echo $this->getSkinUrl('close-div/images/atnt.png')?>" style="margin:0px; padding:0px; " onClick="document.getElementById('p1').style.display='none'"   />

				

			</a>

         </div>

		 

		 

		  <div style="    float:left; ">

            <a id="myHeader2" href="javascript:showonlyone('newboxes2');" >

			

				<img src="<?php echo $this->getSkinUrl('close-div/images/sprint.png')?>" style="margin:0px; padding:0px; " onClick="document.getElementById('p1').style.display='none'"   />

				

			</a>

         </div>

		 

		  <div style="    float:left; ">

            <a id="myHeader3" href="javascript:showonlyone('newboxes3');" >

			

				<img src="<?php echo $this->getSkinUrl('close-div/images/verizon.png')?>" style="margin:0px; padding:0px; " onClick="document.getElementById('p1').style.display='none'"   />

				

			</a>

         </div>

		 

		  <div style="  float:left; ">

            <a id="myHeader4" href="javascript:showonlyone('newboxes4');" >

			

				<img src="<?php echo $this->getSkinUrl('close-div/images/t-mobile.png')?>" style="margin:0px; padding:0px; " onClick="document.getElementById('p1').style.display='none'"   />

				

			</a>

         </div>

		  

		  <div style="  float:left; ">

            <a id="myHeader5" href="javascript:showonlyone('newboxes5');" >

			

				<img src="<?php echo $this->getSkinUrl('close-div/images/factory-unlock.png')?>" style="margin:0px; padding:0px; " onClick="document.getElementById('p1').style.display='none'"   />

				

			</a>

         </div>

		 

		 

		 

		 

         <div class="newboxes" id="newboxes1" style="  display: none;  margin-top:0px; max-width: 1024px; width:100%; height:1100px; z-index:1111;"> 

  <div style="max-width:1000px; width:100%; height:100%; padding: 0px; margin:0px; ">		

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sellit-subcat')->toHtml(); ?>

<!--<iframe src=""  frameborder="0" scrolling="no" allowtransparency="true"  marginwidth="0" marginheight="0" align="left" hspace="0" vspace="0"  style="height:1050px; position:absolute; max-width:1000px; width:100%; margin:0px; padding:0px; border:0px; "></iframe>-->

</div> 



</div>

      

	    <div class="newboxes" id="newboxes2" style="  display: none;  margin-top:0px; width: 1024px; height:1100px; z-index:1111;"> 

  <div style="max-width:1000px; width:100%; height:100%; padding: 0px; margin:0px; ">			



<iframe src="sell-htc-sprint.php"  frameborder="0" scrolling="no" allowtransparency="true"  marginwidth="0" marginheight="0" align="left" hspace="0" vspace="0"  style="height:1150px; position:absolute; width:1000px; margin:0px; padding:0px; border:0px; "></iframe>

</div> 



</div>

 

         <div class="newboxes" id="newboxes3" style="  display: none;  margin-top:0px; width: 1200px; height:1100px; z-index:1111;"> 

  <div style="width:1100px; height:100%; padding: 0px; margin:0px; ">		

  

<iframe src="sell-htc-verizon.php"  frameborder="0" scrolling="no" allowtransparency="true"  marginwidth="0" marginheight="0" align="left" hspace="0" vspace="0"  style="height:1150px; position:absolute; width:1000px; margin:0px; padding:0px; border:0px; "></iframe>

</div> 



</div>

 

   <div class="newboxes" id="newboxes4" style="  display: none;  margin-top:0px; width: 1200px; height:1100px; z-index:1111;"> 

  <div style="width:1100px; height:100%; padding: 0px; margin:0px; ">	

  	

<iframe src="sell-htc-tmobile.php"  frameborder="0" scrolling="no" allowtransparency="true"  marginwidth="0" marginheight="0" align="left" hspace="0" vspace="0"  style="height:1150px; position:absolute; width:1100px; margin:0px; padding:0px; border:0px; "></iframe>

</div> 



</div>

 

  

   <div class="newboxes" id="newboxes5" style="  display: none;  margin-top:0px; width: 1200px; height:1100px; z-index:1111;"> 

  <div style="width:1100px; height:100%; padding: 0px; margin:0px; ">				



<iframe src="sell-htc-factory.php"  frameborder="0" scrolling="no" allowtransparency="true"  marginwidth="0" marginheight="0" align="left" hspace="0" vspace="0"  style="height:1150px; position:absolute; width:1100px; margin:0px; padding:0px; border:0px; "></iframe>

</div> 



</div>

 

 

 </td>



  



 </tr>

 </table>               
                    
            </div>