<?php /*?><section class="products_heading">Or Choose From Our Most Popular Apple Certified Repairs</section>
                        <section id="wn">
      <section id="lyr1">
      <ul>
        <li><a href="product.html"><span>iPhone 3G</span></a></br><a href="product.html"><img src="<?php echo $this->getSkinUrl('')?>images/prod_1.png" width="100" height="183"></a></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
      <li><span>iPhone 3G</span></br><img src="<?php echo $this->getSkinUrl('images/prod_1.png')?>" width="100" height="183"></li>
     </ul>
        </section></section>
<section id="scrollLinks"></section>
<section class="mid_banner"><img src="<?php echo $this->getSkinUrl('images/center_banner.jpg')?>" width="802" height="158"></section><?php */?>