<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-1.2.6.min.js')?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-ui-personalized-1.5.2.packed.js')?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/sprinkle.js')?>"></script>

<table style="max-width:1024px; width:100%;">

	<tr>

	<td style="width:140px; vertical-align:top;">

		<img src="<?php echo $this->getSkinUrl('images/16gb.png')?>"/>

	</td>

	<td style="max-width:850px;  width:100%; vertical-align:top;">

	<div style="font-family:Helvetica; font-size:32px; margin-top:10px;">Apple iPhone 4S 16GB (AT&T/Unlocked)

	</div>

	<div style="font-family:Helvetica; font-size:22px; margin-top:30px; color:#333333;">1. What shape is it in?

	</div>

        <div id="tabvanilla" class="widget">



            <ul class="tabnav">

                <li>

					<a href="#popular">

						<div style="padding:5px 0px 0px 30px;" >

							<font style="color:#eaba00; font-family:Helvetica; font-size:20px;">Broken</font><br />

 

							<span style="color:#333; font-family:Helvetica; font-size:12px; width:100px;">Does not turn on or has serious <br /><strong>physical damage</strong></span>

						</div> 

					</a>

				</li>

                <li ><a href="#recent">

				<div style="padding:5px 0px 0px 30px;" >

							<font style="color:#eaba00; font-family:Helvetica; font-size:20px;">Good</font><br />

 

							<span style="color:#333; font-family:Helvetica; font-size:12px; width:100px;"><strong>Normal signs</strong> of use  </span>

						</div> 

				</a></li>

                <li><a href="#featured">

				<div style="padding:5px 0px 0px 30px;" >

							<font style="color:#eaba00; font-family:Helvetica; font-size:20px;">Flawless</font><br />

 

							<span style="color:#333; font-family:Helvetica; font-size:12px; width:100px;">Looks like it's <strong>never been used</strong>  </span>

						</div> 

				

				 </a></li>

            </ul>



            <div id="popular" class="tabdiv">

					 <div style="max-width:800px; width:100%; height:100%;">

					 <img src="<?php echo $this->getSkinUrl('images/line-1.png')?>" />

					 <div style="background:#f9f9f9; max-width:800px;  width:100%; height:150px;">

					 	<div style="padding:10px 0px 0px 50px; font-size:14px; color:#333;">

							Your iPhone is in this condition if <strong>any</strong> of the following are true:

							<ul>

								<li>Does not power on</li>

								<li>Broken or cracked LCD screen or glass</li>

								<li>Missing buttons (power, home, ringer, volume)</li>

								<li>Broken or cracked hardware (charging ports, casing, etc.)</li>

								<li>Housing separation beyond the width of a nickel</li>

							</ul>

						</div>

					 

					 </div>

					 

					 <div style="max-width:800px; width:100%; margin-top:20px; border:1px solid #333;">

					 <center>

					 		<div style="font-family:Helvetica; color:#8f8f8f; font-size:28px; padding-top:25px;">Your Bumblebee Offer</div>

							

							<div style="font-family:Helvetica; color:#666; font-size:56px; padding-top:25px;"><strong>$85</strong></div>

							

							<div style="padding-top:25px;"><img src="<?php echo $this->getSkinUrl('images/ad2box.png')?>" /></div>

							

							<div style="font-family:Helvetica; color:#5c7d8d; font-size:18px; font-weight:bold; padding-top:25px; padding-left:30px; float:left;">Why sell to A20</div><br /><br />





							

							<div style="font-family:Helvetica; color:#666; font-size:48px; padding:25px 0; width:100%;">

							

								<table>

									<tr>	

										<td style="font-family:Helvetica; color:#666; font-size:14px; width:225px; ">

											&bull;30 day offer guarantee<br />



											&bull;Free shipping

										</td>

										<td style="font-family:Helvetica; color:#666; font-size:14px; width:225px;  ">

											&bull;Fast payment

<br />



											&bull;Free data wipe

										</td>

										<td style="font-family:Helvetica; color:#666; font-size:14px; width:225px;  ">

											&bull;Step by step updates<br />



											&bull;No listing hassles

										</td>

									</tr>

								</table>

							

							</div>

							

						</center>

					 </div>

					 

					 </div>

					 

            </div><!--/popular-->

            

            <div id="recent" class="tabdiv">

               <div style="width:800px; height:100%;">

					 <img src="<?php echo $this->getSkinUrl('images/line-2.png')?>" />

					 <div style="background:#f9f9f9; width:800px; height:70px;">

					 	<div style="padding:10px 0px 0px 50px; font-size:14px; color:#333;">

							Your iPhone is in great working order with some minor cosmetic signs of wear. Your iPhone has no cracks or missing buttons (power, home, ringer, and/or volume).

							 

						</div>

					 

					 </div>

					 

					 <div style="width:800px; margin-top:20px; border:1px solid #333;">

					 <center>

					 		<div style="font-family:Helvetica; color:#8f8f8f; font-size:28px; padding-top:25px;">Your Bumblebee Offer</div>

							

							<div style="font-family:Helvetica; color:#666; font-size:56px; padding-top:25px;"><strong>$277</strong></div>

							

							<div style="padding-top:25px;"><img src="<?php echo $this->getSkinUrl('images/ad2box.png')?>" /></div>

							

							<div style="font-family:Helvetica; color:#5c7d8d; font-size:18px; font-weight:bold; padding-top:25px; padding-left:30px; float:left;">Why sell to A20</div><br /><br />





							

							<div style="font-family:Helvetica; color:#666; font-size:48px; padding:25px 0; width:100%;">

							

								<table>

									<tr>	

										<td style="font-family:Helvetica; color:#666; font-size:14px; width:225px; ">

											&bull;30 day offer guarantee<br />



											&bull;Free shipping

										</td>

										<td style="font-family:Helvetica; color:#666; font-size:14px; width:225px;  ">

											&bull;Fast payment

<br />



											&bull;Free data wipe

										</td>

										<td style="font-family:Helvetica; color:#666; font-size:14px; width:225px;  ">

											&bull;Step by step updates<br />



											&bull;No listing hassles

										</td>

									</tr>

								</table>

							

							</div>

							

						</center>

					 </div>

					 

					 </div>

            </div><!--/recent-->

            

            <div id="featured" class="tabdiv">

                <div style="max-width:800px; width:100%; height:100%;">

					 <img src="<?php echo $this->getSkinUrl('images/line-3.png')?>" />

					 <div style="background:#f9f9f9; max-width:800px; width:100%; height:120px;">

					 	<div style="padding:10px 0px 0px 50px; font-size:14px; color:#333;">

							Your iPhone is in this condition if <strong>all</strong> of the following are true:

							<ul>

								<li>Works perfectly</li>

								<li>No noticeable flaws, still in its package or looks like new</li>

								<li>Has zero scratches</li>

								<li>Has no dust under the glass</li>

			 

							</ul>

						</div>

					 

					 </div>

					 

					 <div style=" max-width:800px; width:100%; margin-top:20px; border:1px solid #333;">

					 <center>

					 		<div style="font-family:Helvetica; color:#8f8f8f; font-size:28px; padding-top:25px;">Your Bumblebee Offer</div>

							

							<div style="font-family:Helvetica; color:#666; font-size:56px; padding-top:25px;"><strong>$290</strong></div>

							

							<div style="padding-top:25px;"><img src="<?php echo $this->getSkinUrl('images/ad2box.png')?>" /></div>

							

							<div style="font-family:Helvetica; color:#5c7d8d; font-size:18px; font-weight:bold; padding-top:25px; padding-left:30px; float:left;">Why sell to A20</div><br /><br />





							

							<div style="font-family:Helvetica; color:#666; font-size:48px; padding:25px 0; width:100%;">

							

								<table>

									<tr>	

										<td style="font-family:Helvetica; color:#666; font-size:14px; width:225px; ">

											&bull;30 day offer guarantee<br />



											&bull;Free shipping

										</td>

										<td style="font-family:Helvetica; color:#666; font-size:14px; width:225px;  ">

											&bull;Fast payment

<br />



											&bull;Free data wipe

										</td>

										<td style="font-family:Helvetica; color:#666; font-size:14px; width:225px;  ">

											&bull;Step by step updates<br />



											&bull;No listing hassles

										</td>

									</tr>

								</table>

							

							</div>

							

						</center>

					 </div>

					 

					 </div>

            </div><!--featured-->



        </div><!--/widget-->



<!--/featuredvid-->



</td>

</tr>

</table>