<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Welcome To Bumblebee</title>
<link href="style.css" rel="stylesheet" type="text/css">
</head>

<body>
<section id="main_container">
	<section id="contaner"><span>Bumblebee Wireless'' Leaders in Buying, Selling, Repairing and Customizing Handheld Electronics. | Click - Ship - Fix - Return</span>
    <section class="top_link">
    	<ul>
        <li><a href="#">Log In</a></li>
        <li><a href="#">Checkout</a></li>
        <li><a href="#">My Cart</a></li>
        <li><a href="#">My Account</a></li></ul></section></section></section>
        <section id="center_main_container">
        <section id="center_container"><section id="header"><section id="logo_containe">
        <section class="logo"><a href="index.html"><img src="images/logo.jpg" width="416" height="98" border="0"></a></section>
        <section id="fb_icons_containe"><section id="live_chat_container"><section class="search_container">
        	<section class="search_btn"><img src="images/search_btn.jpg" width="20" height="20"></section>
            <section class="search">
              <input name="textfield" type="text" class="search_fld" id="textfield">
            </section></section><section class="live_chat"><img src="images/live_chat.jpg" width="57" height="54">Online Chat</section></section>
            <section class="phone_no">Call us toll-free <span>1.800.220.4888</span></section><section id="topsocial">
            <a href="#"><img src="images/fb_icon.jpg" width="25" height="25"></a>
            <a href="#"><img src="images/twiter.jpg" width="25" height="25"></a>
            <a href="#"><img src="images/youtube.jpg" width="25" height="25"></a></section></section><section id="top_menu_container">
            <nav id="topmenu">
	<ul>
    <li class="home"><a href="#" class="home"><img src="images/home_icon.png" width="18" height="18" alt=""></a></li>
	  <li><a href="category.html">Repair It</a><a href="#"></a>
	    <ul>
        <h1>Full Service</h1>
	      <li><a href="#"><strong>Apple</strong><br>iPhone to Mac</a></li>
          <li><a href="#"><strong>Cell Phone</strong><br>Htc to Samsung</a></li>
          <li><a href="#"><strong>Pc Laptop</strong><br>Dell to Toshiba</a></li>
          <li><a href="#"><strong>Game Consoles</strong><br>Hbox to Kindle</a></li>
          <li><a href="#"><strong>Handled Tablet</strong><br>Samsung to Kindle</a></li>  
	        
	      </ul>
	    </li>
	  <li><a href="#">Insure It</a></li>
		<li><a href="#">Buy It</a></li>
        <li><a href="#">Sell It</a></li>
        <li><a href="#">Unlock It</a></li>
        <li><a href="#">Bling It</a></li>
        <li><a href="#">Skin It</a></li>
        <li><a href="#">Prepay</a></li>
        <li><a href="#">Buzz</a></li>
        <li><a href="#">About Us</a></li>
        <li class="last">0 item(s)-$0</li>
	</ul>
</nav>
            </section>
            
<select name="menu" onChange="window.location=this.value" id="topmenu">
<option>Menu</option>
<option value="index.html">Home</option>
<option value="index.html">Home</option>
<option value="index.html">Home</option>
<option value="index.html">Home</option>
</select>

</section></section>
<span class="clear"></span>
<section id="banner_container">



</section>
<section id="center_mid_container">
	<section id="category_container">
                    	<section class="category_heading">Select your Laptop for Repair</section>
                         <section class="categorysub_heading">Click on your Manufacture Below</section>
                        <section id="categorylist-container">
      <section id="category-listing">
      <ul>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
<li><a href="product.html"><img src="images/prod_1.png" height="183"></a></br><a href="product.html"><span>iPhone 3G</span></a></li>
       
       </ul>
        </section>
        </section>
</section>



                    </section>
<section id="footer_main_container">
<section id="why_shop_with_us_container"><img src="images/why_shop_with_us.png" width="179" height="64"><section class="why_shop">
	<ul>
    	<li><a href="#">Certified Mac Technicians</a></li>
        <li><a href="#">Certified Mac Technicians</a></li>
        <li><a href="#">Certified Mac Technicians</a></li>
        <li><a href="#">Certified Mac Technicians</a></li>
        <li><a href="#">Certified Mac Technicians</a></li>
        <li><a href="#">Certified Mac Technicians</a></li></ul></section></section><section class="footer_container">
        	<section  class="footer_link_container">
            	<section class="shop_heading">Services</section>
                	<section class="footer_link">
                    <ul>
                    	<li><a href="#">Apple Repair</a></li>
                    	<li><a href="#">Laptop Repair</a></li>
                    	<li><a href="#">Tablet Repair</a></li>
                    	<li><a href="#">Cell Phone Repair</a></li>
                    	<li><a href="#">Game Console Repair</a></li>
                    	<li><a href="#">Sell your Gadget</a></li>
                    	<li><a href="#">Protect your Gadget</a></li></ul></section></section><section  class="footer_link_container">
            	<section class="shop_heading">Shop</section>
                	<section class="footer_link">
                    <ul>
                    	<li><a href="#">iPhone Accessories</a></li>
                    	<li><a href="#">iPod Accessories</a></li>
                    	<li><a href="#">iPad Accessories</a></li>
                    	<li><a href="#">Tablet Accessories</a></li>
                    	<li><a href="#">Samsumg Accessories</a></li>
                    	<li><a href="#">Bling your Gadget</a></li>
                    	<li><a href="#">Skin your Gadget</a></li>
                    	<li><a href="#">Buy a Used Gadget</a></li></ul></section></section><section class="footer_img"><img src="images/footer_img.jpg" width="230" height="141">We Cover all of the USA.</section><section  class="footer_link_container">
            	<section class="shop_heading">Connect</section>
                	<section class="footer_link">
                    <ul>
                    	<li><a href="#">Like on Facebook</a></li>
                    	<li><a href="#">Follow Us on Twitter</a></li>
                    	<li><a href="#">youtube Channel</a></li>
                    	<li><a href="#">Store Locations</a></li>
                    	<li><a href="#">Franchise Opportunities</a></li>
                    	<li><a href="#">Sell your Gadget</a></li>
                    	<li><a href="#">Contact Us</a></li>
                    	<li><a href="#">Write a Review</a></li></ul></section></section><section  class="footer_link_container">
            	<section class="shop_heading">Help</section>
                	<section class="footer_link">
                    <ul>
                    	<li><a href="#">About Us</a></li>
                    	<li><a href="#">Terms & Conditions</a></li>
                    	<li><a href="#">Customer Reviews</a></li>
                    	<li><a href="#">Warranty Policy</a></li>
                    	<li><a href="#">Return Policy</a></li>
                    	<li><a href="#">FAQ'w</a></li>
                    	<li><a href="#">Contact Us</a></li>
                    	<li><a href="#">Sitemap</a></li></ul></section></section></section>
                        <section class="copy_right">Bumblebee Wireless'' Leaders in Buying, Selling, Repairing and Customizing Handheld Electronics. | Click - Ship - Fix - Return</section></section></section></section>

</body>
</html>
