<script type="text/javascript" src="<?php echo $this->getSkinUrl('close-div/jquery.min.js')?>"></script>
<script type="text/javascript">
 function showonlytwo(thechosenone) {
     $('.newboxestwo').each(function(index) {
          if ($(this).attr("id") == thechosenone) {
               $(this).show(200);
          }
          else {
               $(this).hide(200);
          }
     });
}
</script>
<style type="text/css">

span.link {
    	position: relative;
}

    span.link a span {
    	display: none;
		font: 12px "Arial",sans-serif !important;
}

span.link a:hover {
    	font-size: 99%;
    	font-color: #000000;
}

span.link a:hover span { 
   display: block;
position: absolute;
margin-top: 0px;
margin: 0px;
width: 265px;
padding: 15px;
z-index: 100;
color: #494949;
background: none repeat scroll 0% 0% #fff;
font: 12px "Arial",sans-serif;
text-align: left;
text-decoration: none;
border: 2px solid #FCE63C;
border-radius: 5px;
}
span.link a:hover span strong{
	font-size:12px;
}
span.link a:hover span img{
	vertical-align:middle;
}
#selectdevice {display:block; float:left; font-size:20px; margin:10px 0; color:333333;}
</style>
<style>
.list
{
width:1050px; height:100%; margin:0px;
}
.list div a img
{
 transition: opacity .5s;
-moz-transition: opacity .5s; /* Firefox 4 */
-webkit-transition: opacity .5s; /* Safari and Chrome */
-o-transition: opacity .5s; /* Opera */

}
.list:hover div a img
{
opacity:0.5; 
}

.list div a img:hover
{transition: opacity .5s;
-moz-transition: opacity .5s; /* Firefox 4 */
-webkit-transition: opacity .5s; /* Safari and Chrome */
-o-transition: opacity .5s; /* Opera */

}
.list div a img:hover{opacity:1;}
.list div a.active{opacity:1 !important;}
#subcateswitcher {margin:0px; padding:0px; padding-right:20px; float:left; text-align:center; font-weight:bold; color:#4C4C4C;}

</style>
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script>
$(function () {
$(".somelink a").click(function (e) {
e.preventDefault();
$(".somelink a").addClass("active").not(this).removeClass("active");
});
});
</script>

<?php $level = $this->getCurrentCategory()->getParentCategory()->getLevel();
if($level > 1){ $cellphonee = $this->getCurrentCategory()->getParentCategory()->getName();
//echo  $cellphonee ;  ?> 
<?php if ($cellphonee=='Cell Phones'):?>            
<div style="width:100%; display:block; margin:15px 0 0; float:left;">
		<div style="float:left;">
		<!-- Place the following code in the head section of your web page -->
<!-- Place this code in the body section of your page -->
<span class="link"><a href="javascript: void(0)">
<font style="color:#000; font-family:Helvetica; font-size:14px; position:relative; width:100%; display:block; margin-bottom:10px;">
Which carrier do I have? </font>
<span><img src="<?php echo $this->getSkinUrl('images/questionmark.png')?>"> &nbsp;<strong>Which carrier do I have? </strong>
<p style="height:3px;">&nbsp;</p>The carrier (service provider) name is typically printed on the outside of the phone or displayed on the phone's start-up screen.<br /><br>
Please note: we do not accept all carriers for this brand of phone.  We only accept phones from Verizon, T-Mobile, Sprint, AT&amp;T, or Factory Unlocked. Any other phones received by Gazelle will have a $0 trade-in value (including carriers such as US Cellular, Virgin Mobile, Cricket and other regional carriers.)
</span></a></span>
</div>
</div>
<?php else:?>
<?php endif;?>
<?php }
    ?>

<div class="list" style=" float:left;">
<table width="100%" height="">
<tr>
<td style="vertical-align:top; float:left;">
 <?php
$_subcategories=$this->getCurrentChildCategories();
if($_subcategories->count()):
$categorycount = 0;
$third=500;
foreach ($_subcategories as $_subcategory):
if($_subcategory->getIsActive()):
$cur_category2nd=Mage::getModel('catalog/category')->load($_subcategory->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_category2nd);
$catName = $this->getCurrentCategory()->getName();
$third++;
?>
<?php if ($catName=='Other carrier'):?>
<style>
a[title]:hover:after {
  content: attr(title);
  padding: 4px 8px;
  color: #333;
  position: absolute;
  left: 0;
  top: 100%;
  white-space: nowrap;
  z-index: 20px;
  -moz-border-radius: 5px;
  -webkit-border-radius: 5px;
  border-radius: 5px;
  -moz-box-shadow: 0px 0px 4px #222;
  -webkit-box-shadow: 0px 0px 4px #222;
  box-shadow: 0px 0px 4px #222;
  background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);
  background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0, #eeeeee),color-stop(1, #cccccc));
  background-image: -webkit-linear-gradient(top, #eeeeee, #cccccc);
  background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);
  background-image: -ms-linear-gradient(top, #eeeeee, #cccccc);
  background-image: -o-linear-gradient(top, #eeeeee, #cccccc);
}
a.tip {
    text-decoration: none
}
a.tip:hover {
    position: relative
}
a.tip span {
    display: none
}
a.tip:hover span {
    padding: 5px 20px 5px 5px;
    display: block;
    z-index: 100;
    background: url(../images/status-info.png) #f0f0f0 no-repeat 100% 5%;
    left: 0px;
    margin: 10px;
    width: 250px;
    position: absolute;
    top: 10px;
    text-decoration: none
}
</style>
<div style="padding: 5px;  color:#4C4C4C; font-family:Helvetica; font-size:12px; font-weight:bold;  text-align:center; float:left; ">
<a href="#" class="tip"><img src="<?php echo $this->getCurrentCategory()->getImageUrl() ?>"/><br><?php echo $this->getCurrentCategory()->getName() ?><span>We don't accept Other Carrier phones for this brand of phone.
We only accept phones from Verizon, T-Mobile, Sprint, AT&T,
or Factory Unlocked. Any other phones received by Gazelle will have a $0 trade-in value.
</span></a>
</div>
<?php else:?>
<div style="padding: 5px;  color:#4C4C4C; font-family:Helvetica; font-size:12px; font-weight:bold;  text-align:center; float:left; ">
            <a id="myHeader1" href="javascript:showonlytwo('newboxestwo<?php echo $third;?>');" <?php if ($this->isCategoryActive($_subcategory)): ?> class="active"<?php endif; ?> >
			
				<img src="<?php echo $this->getCurrentCategory()->getImageUrl() ?>"  onclick="document.getElementById('p<?php echo $third;?>').style.display='none'"   /><br><?php echo $this->getCurrentCategory()->getName() ?></a>
                <?php /*?><?php $displayMode = $this->getCurrentCategory()->getDisplayMode();?>
				<?php if($displayMode == 'PAGE'):?>
   Static block <?php echo $this->getCurrentCategory()->getName() ?>
<?php else: ?>
   				<?php echo $this->getCurrentCategory()->getName() ?>

<?php endif; ?><?php */?>

         </div>
<?php endif;?>
         
		 
	<?php
endif;
endforeach;
endif;
?>	
<?php
$_subcategories=$this->getCurrentChildCategories();
if($_subcategories->count()):
$categorycount = 0;
$third=500;
foreach ($_subcategories as $_subcategory):
if($_subcategory->getIsActive()):
$cur_category2nd=Mage::getModel('catalog/category')->load($_subcategory->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_category2nd);
$catName = $this->getCurrentCategory()->getName();
$third++;
?>		 
 <div class="newboxestwo" id="newboxestwo<?php echo $third;?>" style=" display: none;padding: 5px; margin-top:0px; width: 1024px;  z-index:1111;"> 
 <div style="width:1024px;">		
<?php $displayMode = $this->getCurrentCategory()->getDisplayMode();?>
<?php if($displayMode == 'PAGE'):?>  
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sellit_fourthlevel_listing')->toHtml(); ?>
<?php else: ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sellit_eigthlevel_listing')->toHtml(); ?>
<?php endif; ?>
</div> 
</div>
<?php
endif;
endforeach;
endif;
?>	
</td>
 </tr>
 </table>
 </div>