<form action="<?php echo $this->getUrl('customform/index/send')?>">
    <section class="main_container">
<section class="left_side">
<section class="applications_heading">Bee Squad  Tech Application</section>
<section class="applications_heading2">Applying to Join Our Elite Team</section>
<section class="applications_text">We require the completion of this application before the consideration of an<br>
  individual applying to be one of our awesome iTechs. We have very stringent<br>
  standards for those that are accepted to be licensed Affiliates. Tell us your story,<br>
  we want to hear from you!</section>
  <section class="applications_text"><strong>1.</strong> To make sure we are able to contact you, provide your email address</section>
  <section class="email_frnd">
  <p class="p">Email Address</p>
  <input type="text" class="text_fld">
  </section>
    <section class="email_frnd">
  <p class="p">Confirm Email Address</p>
  <input type="text" class="text_fld">
  </section>
    <section class="applications_text"><strong>2.</strong> Please provide us your contact information.This will also allow us to look at your<br>
    Iocal area to see what type of volume is currently occurring in the market.</section>
    <section class="email_frnd">
    <p class="p">Salutation</p>
    <select name="select" id="select">
    <option>Please Select...</option>
    </select>
    </section>

<section class="form_container">
<section class="first_name">
<p class="p">First Name</p>
<input type="text" class="text_fld">
</section>
<section class="last_name">
<p class="p">Last Name</p>
<input type="text" class="text_fld">
</section>
<section class="email_frnd">
  <p class="p">Street 1</p>
  <input type="text" class="text_fld">
  </section>
  <section class="email_frnd">
  <p class="p">Street 2</p>
  <input type="text" class="text_fld">
  </section>
  <section class="city">
  <p class="p">City</p>
  <input type="text" class="text_fld">
  </section>
    <section class="zipcode">
  <p class="p">Zipcode</p>
  <input type="text" class="text_fld">
  </section>
  <section class="state">
  <p class="p"><strong>State</strong></p>
  <select name="select2" id="select2" class="select_menu">
      <option>Please Select...</option>
  </select>
  </section>
    <section class="country">
  <p class="p"><strong>Country</strong></p>
  <select name="select2" id="select2" class="select_menu">
      <option>Please Select...</option>
  </select>
  </section>
   <section class="email_frnd">
  <p class="p">Phone Number</p>
  <input type="text" class="text_fld">
  </section>
    <section class="applications_text"><strong>3.</strong> As part of the Bumblebee process, all Bee Squad Techs are required to purchase<br>
      a startup kit ranging from $699 to $1499 which includes a full tool supply, startup<br>
      hardware, and licensing agreements. Please select the time line within which you<br>
      will be able to purchase the Bee Squad Launch Kit:</section>
 <section class="options">
  <p class="p">Options</p>
  <select name="select2" id="select2" class="select_menu">
      <option>Please Select...</option>
  </select>
  </section>
  
  <section class="applications_text"><strong>4.</strong> Please provide any additional information that we should konow about, whether<br>
    Your experience in the industry or just general information about youreslf!</section>
 <section class="email_frnd">
  <p class="p">Additional Information</p>
  <input type="text" class="text_fld">
  </section>
   <section class="applications_text"><strong>5.</strong> How did you hear about the opportunity to become a local Bee Squad Technician?</section>
   
   <section class="options">
  <p class="p">Options</p>
  <select name="select2" id="select2" class="select_menu">
      <option>Please Select...</option>
  </select>
  </section>

<section class="submit_container">
<button>Submit Your Application</button>
<input type="submit" value="Submit Your Application">
</section>

</section>
</section>

<section class="right_side"><img src="<?php echo $this->getSkinUrl('images/shirt.jpg')?>"></section>

</section>
</form>