<?php $profiles= $this->getProfiles(); ?>
<?php 
	$currentDesign = Mage::getSingleton('core/design_package')->getPackageName();
	$queryBoxEnabled = Mage::getStoreConfig('payment/generalset/enable_query');
	$query_cust_msg = Mage::getStoreConfig('payment/generalset/query_cust_msg');
	
	//echo 'ok/'.Mage::getStoreConfig('payment/generalset/email_template');die;
?>

 <table>
	
	<tr>
		<td>
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'cim/manage_cards.png';?>" alt="<?php echo $this->__('Manage My Cards') ?>" title="<?php echo $this->__('Manage My Cards') ?>" style="width:37px;height:37px"/>
		</td>
		<td colspan="3">
			<span class="auth_title"><?php echo $this->__('Manage My Cards') ?></span>
		</td>
	</tr>
	
	<tr>
 
		<td colspan="4">
			&nbsp;
		</td>
	</tr>
 </table>
  
  <table>
	<tr>
		<td><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'cim/fam_creditcards.gif';?>" alt="<?php echo $this->__('Add New Card') ?>" title="<?php echo $this->__('Add New Card') ?>" /></td>
	<td class="paddingleft4"><a href="<?php echo $this->getUrl('morecc/index/index',array('_secure'=>true)) ?>"><?php echo $this->__('Add New Card') ?></a>&nbsp; |  &nbsp;</td>
		
		<td><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'cim/i_ma-info.gif';?>" alt="<?php echo $this->__('View Card History') ?>" title="<?php echo $this->__('View Card History') ?>" /></td>
	<td class="paddingleft4"><a href="<?php echo $this->getUrl('morecc/index/viewblocks',array('_secure'=>true)) ?>"><?php echo $this->__('View Card History') ?></a>&nbsp;</td>
	</tr>
</table>

<?php if($profiles->getSize()): ?>
<table class="data-table" id="my-orders-table" >
    <thead>
        <tr>
            <th><?php echo $this->__('Card Number') ?></th>
			<th><?php echo $this->__('Type') ?></th>
			<th style="width:22%"><?php echo $this->__('Bill To') ?></th>
			<th><?php echo $this->__('Created Date') ?></th>
			<th><?php echo $this->__('Exp Date') ?></th>
			
            <th><?php echo $this->__('Action') ?></th>
        </tr>
    </thead>
    <tbody>

	<?php
		$resource = Mage::getSingleton('core/resource');
		$read= $resource->getConnection('core_read');
		$moreccTable = $resource->getTableName('morecc');
		$remainningDays = '';
	?>
    <?php foreach ($profiles as $profile): ?>
	<?php //echo Mage::app()->getLocale()->storeDate(Mage::app()->getStore(), null, true)->toString('Y-MM-dd HH:mm:ss');echo '<br/>';?>
		<?php 
			$currentDate = Mage::app()->getLocale()->storeDate(Mage::app()->getStore(), null, true)->toString('Y-MM-dd');
			$cardExpDate = $profile->getExprMonth().'-'.$profile->getExprYear();
			$generateLastDayExpDate = $profile->getExprYear().'-'.$profile->getExprMonth().'-' . '1';
			
			$lastDaySql  = "SELECT LAST_DAY('$generateLastDayExpDate') as lday";
			$lastDaySqlRes = $read->fetchRow($lastDaySql);
			if(isset($lastDaySqlRes['lday']) && $lastDaySqlRes['lday'] != "")
			{
				$sqlResArr = explode("-",$lastDaySqlRes['lday']);
				if(isset($sqlResArr[2]) && $sqlResArr[2] != "")
				{
					$addNewLastDayExpDate = $profile->getExprYear().'-'.$profile->getExprMonth().'-' . $sqlResArr[2] ;
					$select  = "SELECT DATEDIFF('$currentDate','$addNewLastDayExpDate') AS days from $moreccTable where morecc_id='".$profile->getMoreccId()."'" ; 
					$diffRes = $read->fetchRow($select); 					
					if(isset($diffRes['days']) && $diffRes['days'] != "")
					{
						$remainningDays = ($diffRes['days'] < 0) ? $diffRes['days'] * -1 : $diffRes['days'];
					}
				}
			}
		?>
		
        <tr> 
            <td><?php echo $profile->getNumber() ?>&nbsp;</td>
			<td style="text-align:center;"><?php echo $profile->getCardType() ?>&nbsp;</td>
            <td><?php echo $profile->getName() ?>&nbsp;</td>
			<td style="text-align:center;"><?php echo $profile->getCreatedTime() ?>&nbsp;</td>
			<td style="text-align:center;<?php if($remainningDays < 30){?>color:red;<?php } ?>">
				<?php echo $this->getMonthFormat($profile->getExprMonth());?><?php echo ', '.$profile->getExprYear(); ?>
				<br/>
				<span style="color:red;"><?php if($remainningDays < 30){ echo '( '.Mage::helper('morecc')->__('About to Expire').' )'; }?></span>
			</td>
			<td class="a-center view last"> 
			
			 
												
			<span class="nobr1">
			
			 <a style="float:left;" href="<?php echo $this->getUrl('morecc/index/view', array('id'=>$profile->getMoreccId(),'_secure'=>true)) ?>">
			 	<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'cim//btn_show-hide_icon.gif';?>" alt="<?php echo $this->__('View') ?>" title="<?php echo $this->__('View') ?>" /></a>
			
             <a href="<?php echo $this->getUrl('morecc/index/edit', array('id'=>$profile->getMoreccId(),'_secure'=>true)) ?>">
			 	<img style="padding-left:4px;"  src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'cim/btn_edit.gif';?>"  alt="<?php echo $this->__('Edit') ?>" title="<?php echo $this->__('Edit') ?>"/></a>
				
				
				<a href="javascript:deleteRecord('<?php echo $profile->getMoreccId() ?>','<?php echo $profile->getPayId() ?>','<?php echo $profile->getProfileId() ?>');"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'cim/btn_gm-close.gif';?>"  alt="<?php echo $this->__('Delete') ?>" title="<?php echo $this->__('Delete') ?>"/></a>
			 
			</span>
					
			</td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

 <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have not created any profile yet.') ?></p>
<?php endif ?>

						
<?php if($queryBoxEnabled == 1){?>						
 
	<table> 
		<tr>
			<td>
			<ul>
				<li>
					<div class="field" style="margin-top:10px;">
						<label for="name" style="font-weight:bold;"><?php echo $query_cust_msg; ?></label>
						<div class="input-box" style="margin-bottom:2px;">
							<textarea name="querymessage" style="width:680px;height:200px;" id="querymessage" class="input-text required-entry"></textarea>
						</div>
					</div>
					<div>
			 
					
					<button onclick="askQuery()" title="<?php echo Mage::helper('morecc')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('morecc')->__('Submit') ?></span></span></button>
										 
					</div>
				</li>
			</ul>
			 
				 </td>	
			</tr>
		</table> 
	 
<?php } ?>


<?php if($currentDesign == 'rwd'){?>

<div style="left: -2px; top: 0px; display:none;" id="loading-mask">
    <p id="loading_mask_loaderrwd" class="loaderrwd"><img alt="<?php echo $this->__('Loading...') ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'cim/ajax-loader-tr.gif';?>">  <?php echo $this->__('Please wait...') ?></p>
</div>
<?php } else{ ?>
<div style="left: -2px; top: 0px; display:none;" id="loading-mask">
    <p id="loading_mask_loader" class="loader"><img alt="<?php echo $this->__('Loading...') ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'cim/ajax-loader-tr.gif';?>"> <br/><?php echo $this->__('Please wait...') ?></p>
</div>
<?php } ?>
 
 
<script>
function deleteRecord(recordId,PaymentId,profileId)
{

	if (confirm("<?php echo Mage::helper('ordermanager')->__('Are you sure ?');?>") ) {
       var params = {};  

	   //var url = '<?php //echo Mage::getBaseUrl('web')."morecc/index/deletePaymentProfile/"; ?>';
	   var url = '<?php echo $this->getUrl("morecc/index/deletePaymentProfile/",array('_secure'=>true)); ?>';
	   url = url + '&isAjax=true' ;
	   
	   document.getElementById('loading-mask').style.display = 'block';
	   
	   var str = 'record_id='+recordId + '&payment_id=' + PaymentId + '&profile_id=' +  profileId;
	 
	   new Ajax.Request(url, { 
		   method: 'post',
		   parameters: str,
		   onSuccess: function(transport) {
					try {
						   document.getElementById('loading-mask').style.display = 'none';
                            if (transport.responseText.isJSON()) {

                                var response = transport.responseText.evalJSON()
                                if (response.error) {
                                }
                                else{window.location.reload();}
                            } else {
                                window.location.reload();
                            }
                        }
                        catch (e) {
                            
                        }
		   }
	   }
	   );
    } 
}

</script>

<script>
function askQuery()
{ 
	var message = document.getElementById('querymessage').value ;
	if(message == ""){alert('<?php echo Mage::helper('morecc')->__('Please Enter Message.') ?>');document.getElementById('querymessage').focus();}
	if(message != "" )
	{
		var params = {};   	 
		document.getElementById('loading-mask').style.display = 'block';

		//var url = '<?php //echo Mage::getBaseUrl('web')."morecc/index/askQuery/"; ?>';
		var url = '<?php echo $this->getUrl("morecc/index/askQuery/",array('_secure'=>true)); ?>';
	   	url = url + '&isAjax=true' ;

		var str = 'msg='+message;
			new Ajax.Request(url, {
				method: 'post',
				parameters: str,
				onSuccess: function(transport) {
					document.getElementById('loading-mask').style.display = 'none';
					 var data = transport.responseText.evalJSON();
					   if(data.success==true){
					   		alert(data.msg);
							document.getElementById('querymessage').value = '';	
					   }
					   else{
					   		alert(data.msg);
							document.getElementById('querymessage').value = '';	
					   }
				},
				
				onFailure: function()
				{	//alert("not worked");  
				}
			});		
   		}
}

</script>