<section class="page_main_container">
<section class="page_left_side">
<section class="newpage_heading">Contact Us</section>
<section class="newpage_text">Please fill out form below and one of our Bee Squad™ Representatives will contact you shortly.</section>
<section class="newpageform_container">
<span class="require"><img src="<?php echo $this->getSkinUrl('images/contactstar.jpg')?>" width="18" height="11">indicates required</span>
<style>
.std p {display:none;}
#webform_2 .fieldset{ border: 0px solid #bbafa0; margin: 0px 0;  padding: 0px}
#webform_2 .std ul {padding-left:0px;}
.std ul {padding-left:0px !important;}
#webform_2 .form-list .field{max-width: 595px; margin-bottom:20px;}
#webform_2 .form-list .input-box { max-width: 600px !important;}
#webform_2  .form-list input.input-text  { max-width: 600px !important; background: url("<?php echo $this->getSkinUrl('images/contactstar.jpg')?>") no-repeat scroll right center rgba(0, 0, 0, 0);
    border: 1px solid #878787;
    box-sizing: border-box;
    float: left;
    height: 29px;
    line-height: 29px;
    margin-bottom: 5px;
    outline: medium none;
    padding: 0 25px 0 10px;
    width: 100%;}
#webform_2 .form-list textarea {float: left;
width: 100%;
border: 1px solid #878787;
line-height: 20px;
height: 134px;
background: url("<?php echo $this->getSkinUrl('images/contactstar.jpg')?>") no-repeat scroll right 8px transparent;
margin-bottom: 10px;
outline: medium none;
padding: 0px 25px 0px 10px;
box-sizing: border-box;
max-width:600px;}
#webform_2 .buttons-set {
    border-top: 0 solid #e4e4e4;
    clear: none;
	margin:0px;}
</style>
<?php
/**
 * @author         Vladimir Popov
 * @copyright      Copyright (c) 2014 Vladimir Popov
 */

// in case redirect fails
if (Mage::registry('redirect_url')) {
    ?>
    <meta http-equiv="refresh" content="0;url=<?php echo Mage::registry('redirect_url') ?>">
    <script type="text/javascript">
        window.location = '<?php echo Mage::registry('redirect_url')?>';
    </script>
    
<?php
}

// get temporary data
$tmpData = Mage::getSingleton('core/session')->getData('webform_result_tmp_' . $this->getWebform()->getId());
$tmpResult = new Varien_Object();
if (!empty($tmpData['field']) && is_array($tmpData['field'])) {
    foreach ($tmpData['field'] as $field_id => $value) {
        $tmpResult->setData('field_' . $field_id, $value);
    }
}

if ($this->getWebform()->getIsActive() == VladimirPopov_WebForms_Model_Webforms::STATUS_DISABLED || !$this->isDirectAvailable()) {
    echo $this->getNotAvailableMessage();
} else {

    if (Mage::registry('show_form_name')) {
        ?>
        <div class="page-title">
            <h1><?php echo $this->getWebform()->getName(); ?></h1>
        </div>
    <?php } ?>

    <?php if ($this->isAjax()) { ?>
        <div id="webform_<?php echo $this->getWebform()->getId() ?>_success_text" class="std webforms-success-text"
             style="display:none"></div>
    <?php } ?>

    <?php
    if (Mage::registry('show_success')) {
        ?>
        <div class="std webforms-success-text">
            <?php echo $this->getWebform()->getSuccessText() ?>
        </div>
    <?php
    } else {
        ?>

        <div id="webform_<?php echo $this->getWebform()->getId() ?>_form">

            <?php if ($this->getWebform()->getDescription()) { ?>
                <div class="std">
                    <?php echo $this->getWebform()->getDescription(); ?>
                </div>
            <?php } ?>

            <?php if ($this->isAjax()) { ?>
                <iframe id="webform_<?php echo $this->getWebform()->getId() ?>_iframe"
                        name="webform_<?php echo $this->getWebform()->getId() ?>_iframe"
                        style="width:0;height:0;border:0;position:absolute"></iframe>
            <?php } ?>

            <form action="<?php echo $this->getFormAction() ?>" method="post"
                  name="webform_<?php echo $this->getWebform()->getId() ?>"
                  id="webform_<?php echo $this->getWebform()->getId() ?>" enctype="<?php echo $this->getEnctype() ?>"
                  class="webforms-<?php echo $this->getWebform()->getCode() ?>"
                  <?php if ($this->isAjax()) { ?>target="webform_<?php echo $this->getWebform()->getId() ?>_iframe"<?php } ?>>


                <input type="hidden" name="submitWebform_<?php echo $this->getWebform()->getId() ?>" value="1"/>
                <input type="hidden" name="webform_id" value="<?php echo $this->getWebform()->getId() ?>"/>

                <?php if (is_array($this->getData('hidden'))) {
                    foreach ($this->getData('hidden') as $key => $value) {
                        ?>
                        <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>"/>
                    <?php
                    }
                }?>

                <?php if (count($this->getWebform()->_getHidden())) {
                    foreach ($this->getWebform()->_getHidden() as $field) {
                        echo $field->toHtml();
                    }
                } ?>

                <?php
                foreach ($this->getWebform()->_getFieldsToFieldsets() as $fieldset_id => $fieldset) {
                    ?>

                    <div id="fieldset_<?php echo $fieldset_id ?>" class="fieldset fieldset-<?php echo $fieldset_id ?>"
                        <?php if ($fieldset['logic_visibility'] == 'hidden') echo 'style="display:none"'; ?>>

                        <?php if (!empty($fieldset['name'])) { ?>
                            <h2 class="legend"><?php echo $fieldset['name'] ?></h2>
                        <?php } ?>

                        <ul class="form-list">
                            <?php
                            $k = 0;
                            $j = 0;
                            $prev = false;
                            $fields_count = count($fieldset['fields']);
                            foreach ($fieldset['fields'] as $field) {

                                // set temporary value
                                $field->setData('result', $tmpResult);

                                $size_class = "fields";
                                $field_class = "field";
                                if ($field->getSize() == 'wide') {
                                    $size_class = "wide";
                                    $field_class = "";
                                }

                                ?>
                                <?php if ($j % 2 == 0 || $field->getSize() == 'wide' || $prev->getSize() == 'wide') {
                                    $j = 0; ?>
                                    <?php if ($k > 1) { ?></li><?php } ?>
                                    <li <?php if ($size_class == 'wide') { ?>id="field_<?php echo $field->getId() ?>_row" <?php } ?>
                                    class="<?php echo $size_class ?> <?php if ($size_class == 'wide') { ?>webforms-fields-row-<?php echo $field->getId() ?><?php } ?>"
                                    <?php if ($size_class == 'wide' && $field->getData('logic_visibility') == 'hidden') echo 'style="display:none"'; ?>>
                                <?php } ?>
                                <div id="field_<?php echo $field->getId() ?>"
                                     class="<?php echo $field_class ?> webforms-fields-<?php echo $field->getId() ?><?php if ($field->getCode()) { ?> webforms-fields-<?php echo $field->getCode();
                                     }?>"
                                    <?php if ($field->getData('logic_visibility') == 'hidden') echo 'style="display:none"'; ?>>

                                    <?php if ($field->getType() != 'html' && $field->getType() != 'subscribe') { ?>
                                        <label class="newpage_text2" for="field_<?php echo $field->getId() ?>"
                                               <?php if ($field->getRequired()) { ?>class="required"<?php } ?>>
                                            <?php if ($field->getRequired()) { ?>
                                                
                                            <?php } ?>
                                            <?php echo $field->getName() ?>
                                        </label>
                                    <?php } ?>

                                    <div class="input-box">
                                        <?php echo $field->toHtml(); ?>

                                    </div>

                                </div>
                                <?php if ($k == $fields_count - 1) { ?>
                                    </li>
                                <?php } ?>
                                <?php
                                $k++;
                                $j++;
                                $prev = $field;
                            }?>
                        </ul>

                    </div>

                <?php
                } // foreach 'fields_to_fieldsets'
                ?>

                <?php if (Mage::registry('use_captcha')) { ?>
                    <div class="fieldset">
                        <h2 class="legend">Captcha</h2>
                        <ul class="form-list">
                            <li class="fields">
                                <div class="field">
                                    <?php echo $this->getCaptcha()->getHTML() ?>
                                </div>
                            </li>
                        </ul>
                    </div>
                <?php } ?>
<section class="newpage_text2">
    <input type="checkbox" name="checkbox" id="checkbox"> Newsletter - Subscribe and get the latest Buzz on the hottest gadgets and sweet discounts
</section>
                <div class="buttons-set">
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <button type="button" class="submit_botn"
                            id="webform_<?php echo $this->getWebform()->getId() ?>_submit_button"
                            onclick="webform_<?php echo $this->getWebform()->getId() ?>_submit()"
                            title="<?php echo $this->__('submit') ?>">
			<span>
				<span><?php echo $this->__($this->getWebform()->getSubmitButtonText()) ?></span>
			</span>
                    </button>
		<span class="please-wait" id="webform_<?php echo $this->getWebform()->getId() ?>_sending_data"
              style="display:none;">
			<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
                 alt="<?php echo $this->__('Sending...') ?>" title="<?php echo $this->__('Sending...') ?>"
                 class="v-middle"/><span
                id="webform_<?php echo $this->getWebform()->getId() ?>_progress_text"><?php echo $this->__('Sending...') ?></span>
		</span>
                </div>

            </form>

        </div>

        <?php echo $this->getLayout()->createBlock(
            'core/template',
            'webform_' . $this->getWebform()->getId() . '_submit_script',
            array(
                'webform' => $this->getWebform(),
                'ajax' => $this->isAjax(),
                'template' => 'webforms/scripts/submit.phtml',
            )
        )->toHtml();
        ?>

    <?php
    } // if(show_success)
} // is active
?>
</section>
</section>
<section class="right_img"><img src="<?php echo $this->getSkinUrl('images/img1.jpg')?>"></section>
</section>