<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head')?>
<script src="<?php  echo $this->getSkinUrl('js/jquery.min.js')?>"></script>
<?php /*?>    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.0.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.tooltipster.min.js')?>"></script>
    <script>
        $(document).ready(function() {
            $('.tooltip').tooltipster();
        });
    </script><?php */?>
</head>
<body onload="T0=new CngClass('selected');T0.CngClass('t0');
T1=new CngClass('selected1');T1.CngClass('t1');
T2=new CngClass('selected2');T2.CngClass('t2');
T3=new CngClass('selected3');T3.CngClass('t3');
T4=new CngClass('selected4');T4.CngClass('t4');
T5=new CngClass('selected5');T5.CngClass('t5');">
<!--<body onLoad="setTimeout('window.close()', 10000);">
--><div id="main_container">
	<div id="contaner"><span>Bumblebee Wireless&trade; Leaders in Buying, Selling, Repairing and Customizing Wireless Technologies. | <a href="<?php echo $this->getUrl('faq/index/categoryshow/cat_id/3/')?>"> Click – Ship – Get – Paid&trade;</a></span>
    <div class="top_link">
    	<ul>
       <li><?php if (Mage::getSingleton('customer/session')->isLoggedIn()==0): ?>
<a href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo $this->__('Log In') ?></a>
<?php else: ?>
<a href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo $this->__('Log Out') ?></a>
<?php endif ?> </li>
        <li><a href="<?php echo $this->getUrl('checkout')?>">Checkout</a></li>
        <li><a href="<?php echo $this->getUrl('checkout/cart')?>">My Cart</a></li>
        <li><a href="<?php echo $this->getUrl('customer/account/')?>">My Account</a></li>
        </ul></div></div></div>
        <div id="center_main_container">
        <div id="center_container">
        <?php echo $this->getChildHtml('header')?>
<span class="clear"></span>
<div id="banner_container">
</div>
<div id="center_mid_container">
	<div id="category_container">
                    	<!--<div class="category_heading"> <?php echo Mage::getSingleton('cms/page')->getTitle() ?></div>
                         <div class="categorysub_heading">Click on your Manufacture Below</div>-->
                        <div id="categorylist-container">
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('global_messages') ?>
<?php echo $this->getChildHtml('content') ?>   
        </div>
</div>
</div>
<?php echo $this->getChildHtml('footer')?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</div></div>
<script src="<?php echo $this->getSkinUrl('SpryAssets/SpryTabbedPanels.js')?>" type="text/javascript"></script>
<link href="<?php echo $this->getSkinUrl('SpryAssets/SpryTabbedPanels.css')?>" rel="stylesheet" type="text/css" />
 <script type="text/javascript">
var div = new Spry.Widget.TabbedPanels("div");
        </script>
</body>
</html>