<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-1.2.6.min.js')?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-ui-personalized-1.5.2.packed.js')?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/sprinkle.js')?>"></script>



       
                 <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sell-itdefault')->toHtml(); ?>

                

                

            <!--/popular-->

            
