<!DOCTYPE html>
<head>
<?php echo $this->getChildHtml('head')?>
<script src="<?php echo $this->getSkinUrl('js/jquery.min.js')?>"></script>
</head>
<body>
<div id="main_container">
	<div id="contaner"><span>Bumblebee Wireless&trade; Leaders in Buying, Selling, Repairing and Customizing Wireless Technologies. | <a href="<?php echo $this->getUrl('trade-in-gadgets')?>" style="text-decoration:underline">Click - Ship </a> <a href="<?php echo $this->getUrl('repair-it')?>" style="text-decoration:underline">- Fix - Return&trade;</a></span>
    <div class="top_link">
    	<ul>
        <li><?php if (Mage::getSingleton('customer/session')->isLoggedIn()==0): ?>
<a href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo $this->__('Log In') ?></a>
<?php else: ?>
<a href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo $this->__('Log Out') ?></a>
<?php endif ?> </li>
        <li><a href="<?php echo $this->getUrl('onepagecheckout')?>">Checkout</a></li>
        <li><a href="<?php echo $this->getUrl('checkout/cart')?>">My Cart</a></li>
        <li><a href="<?php echo $this->getUrl('customer/account/')?>">My Account</a></li>
        </ul></div></div></div>
        <div id="center_main_container">
        <div id="center_container">
        <?php echo $this->getChildHtml('header')?>
<span class="clear"></span>


<div id="center_mid_container">
     
     <div id="center_mid_containerother">

<div id="left_menu_container">
	<?php echo $this->getChildHtml('left')?>
    </div>
<div id="right_side_container">
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('global_messages') ?>
<?php echo $this->getChildHtml('content') ?>                          
</div></div>
<?php echo $this->getChildHtml('footer')?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>

</div></div>
</body>
</html>