<!DOCTYPE html>
<head>
<?php echo $this->getChildHtml('head')?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-1.10.2.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/homehead.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery-1.7.1.min.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery.min.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/bjqs-1.3.min.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/dw_glidescroll.js')?>" type="text/javascript"></script>
<script type="text/javascript">
if ( DYN_WEB.Scroll_Div.isSupported() ) {
    DYN_WEB.Event.add( window, 'load', function() {
		var wndo = new DYN_WEB.Scroll_Div('wn', 'lyr1');
		wndo.addGlideControls('scrollLinks', 'h', 200, 300);
	});
}

</script>
</head>
<body>
<section id="main_container">
	<section id="contaner"><span>Bumblebee Wireless&trade; Leaders in Buying, Selling, Repairing and Customizing Wireless Technologies. | Click - Ship - Fix - Return&trade;</span>
    <section class="top_link">
    	<ul>
        <li><?php if (Mage::getSingleton('customer/session')->isLoggedIn()==0): ?>
<a href="<?php echo $this->getUrl('customer/account/login') ?>"><?php echo $this->__('Log In') ?></a>
<?php else: ?>
<a href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo $this->__('Log Out') ?></a>
<?php endif ?> </li>
        <li><a href="<?php echo $this->getUrl('checkout')?>">Checkout</a></li>
        <li><a href="<?php echo $this->getUrl('checkout/cart')?>">My Cart</a></li>
        <li><a href="<?php echo $this->getUrl('customer/account/')?>">My Account</a></li>
        </ul></section></section></section>
        <section id="center_main_container">
        <section id="center_container">
        <?php echo $this->getChildHtml('header')?>
<span class="clear"></span>

<?php      $_base_url = $this->helper('core/url')->getHomeUrl();
                $class = str_replace($_base_url, '', $this->helper('core/url')->getCurrentUrl());
                $pagetitle = str_replace('.html', '', $class);
                $page = str_replace('industries/', '', $pagetitle);
				if($page=="home/"){
                ?>
<section id="banner_container">
<section id="banner-fade">
        <ul class="bjqs">
         <li><a href="<?php echo $this->getUrl('repair-it')?>"><img src="<?php echo $this->getSkinUrl('images/banner0.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('repair-it')?>"><img src="<?php echo $this->getSkinUrl('images/banner1.png')?>" width="1024" height="350"></a></li>
           <li><a href="<?php echo $this->getUrl('')?>"><img src="<?php echo $this->getSkinUrl('images/pre-paid banner.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('trade-in-gadgets')?>"><img src="<?php echo $this->getSkinUrl('images/banner2.png')?>" width="1024" height="350"></a></li>
          <li><a href="http://www.skinit.com/?affiliate=comjct&utm_source=comjct&utm_medium=affil" target="_blank"><img src="<?php echo $this->getSkinUrl('images/banner9.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('apple-ipad-repair.html')?>"><img src="<?php echo $this->getSkinUrl('images/banner3.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('do-it-yourself-kits.html')?>"><img src="<?php echo $this->getSkinUrl('images/banner4.png')?>" width="1024" height="350"></a></li>
          <li><a href=" http://us.protectyourbubble.com/gadget-insurance/iphone-insurance/?SSAID=919343" target="_blank"><img src="<?php echo $this->getSkinUrl('images/banner5.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('color-conversion-kits.html')?>"><img src="<?php echo $this->getSkinUrl('images/banner6.jpg')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('')?>"><img src="<?php echo $this->getSkinUrl('images/banner8.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('trade-in-gadgets')?>"><img src="<?php echo $this->getSkinUrl('images/banner7.png')?>" width="1024" height="350"></a></li>
        </ul>
    </section>
</section>
<section id="center_mid_container">
     <?php }elseif($page==""){?>
  <section id="banner_container">
<section id="banner-fade">
        <ul class="bjqs">
         <li><a href="<?php echo $this->getUrl('repair-it')?>"><img src="<?php echo $this->getSkinUrl('images/banner0.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('repair-it')?>"><img src="<?php echo $this->getSkinUrl('images/banner1.png')?>" width="1024" height="350"></a></li>
           <li><a href="<?php echo $this->getUrl('')?>"><img src="<?php echo $this->getSkinUrl('images/pre-paid banner.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('trade-in-gadgets')?>"><img src="<?php echo $this->getSkinUrl('images/banner2.png')?>" width="1024" height="350"></a></li>
          <li><a href="http://www.skinit.com/?affiliate=comjct&utm_source=comjct&utm_medium=affil" target="_blank"><img src="<?php echo $this->getSkinUrl('images/banner9.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('apple-ipad-repair.html')?>"><img src="<?php echo $this->getSkinUrl('images/banner3.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('do-it-yourself-kits.html')?>"><img src="<?php echo $this->getSkinUrl('images/banner4.png')?>" width="1024" height="350"></a></li>
          <li><a href=" http://us.protectyourbubble.com/gadget-insurance/iphone-insurance/?SSAID=919343" target="_blank"><img src="<?php echo $this->getSkinUrl('images/banner5.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('color-conversion-kits.html')?>"><img src="<?php echo $this->getSkinUrl('images/banner6.jpg')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('')?>"><img src="<?php echo $this->getSkinUrl('images/banner8.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('trade-in-gadgets')?>"><img src="<?php echo $this->getSkinUrl('images/banner7.png')?>" width="1024" height="350"></a></li>
        </ul>
    </section>
</section>
<section id="center_mid_container">
    <?php }elseif($page=="index.php"){?>
  <section id="banner_container">
<section id="banner-fade">
        <ul class="bjqs">
         <li><a href="<?php echo $this->getUrl('repair-it')?>"><img src="<?php echo $this->getSkinUrl('images/banner0.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('repair-it')?>"><img src="<?php echo $this->getSkinUrl('images/banner1.png')?>" width="1024" height="350"></a></li>
           <li><a href="<?php echo $this->getUrl('')?>"><img src="<?php echo $this->getSkinUrl('images/pre-paid banner.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('trade-in-gadgets')?>"><img src="<?php echo $this->getSkinUrl('images/banner2.png')?>" width="1024" height="350"></a></li>
          <li><a href="http://www.skinit.com/?affiliate=comjct&utm_source=comjct&utm_medium=affil" target="_blank"><img src="<?php echo $this->getSkinUrl('images/banner9.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('apple-ipad-repair.html')?>"><img src="<?php echo $this->getSkinUrl('images/banner3.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('do-it-yourself-kits.html')?>"><img src="<?php echo $this->getSkinUrl('images/banner4.png')?>" width="1024" height="350"></a></li>
          <li><a href=" http://us.protectyourbubble.com/gadget-insurance/iphone-insurance/?SSAID=919343" target="_blank"><img src="<?php echo $this->getSkinUrl('images/banner5.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('color-conversion-kits.html')?>"><img src="<?php echo $this->getSkinUrl('images/banner6.jpg')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('')?>"><img src="<?php echo $this->getSkinUrl('images/banner8.png')?>" width="1024" height="350"></a></li>
          <li><a href="<?php echo $this->getUrl('trade-in-gadgets')?>"><img src="<?php echo $this->getSkinUrl('images/banner7.png')?>" width="1024" height="350"></a></li>
        </ul>
    </section>
</section>
<section id="center_mid_container">
	 <?php }else{ ?>   
     <section id="center_mid_containerother">
    <?php }?>

<section id="left_menu_container">
	<?php echo $this->getChildHtml('left')?>
    </section>
<section id="right_side_container">
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('global_messages') ?>
<?php echo $this->getChildHtml('content') ?>                          
</section></section>
<?php echo $this->getChildHtml('footer')?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</section></section>
<script class="secret-source">
jQuery(document).ready(function($) {

          $('#banner-fade').bjqs({
            height      : 350,
            width       : 1024,
            responsive  : true
          });

        });
</script>
</body>
</html>