<div style="width:100%; height:100%; padding: 0px; margin:0px; float:left; ">
<section id="selectdevice">Select your 
<?php if ($currentUrl = $this->helper('core/url')->getCurrentUrl()=='http://bumblebeewireless.com/preview/sell-my-drone'):
?>
 <?php echo Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName() ?> <?php $level = $this->getCurrentCategory()->getParentCategory()->getLevel();
if($level > 1){                 
    echo $this->getCurrentCategory()->getParentCategory()->getName();
    }
    else{
    echo $this->escapeHtml($_category->getName());
    } ?> to sell.
<?php else :?>    
<?php $level = $this->getCurrentCategory()->getParentCategory()->getLevel();
if($level > 1){                 
    echo $this->getCurrentCategory()->getParentCategory()->getName();
    }
    else{
    echo $this->escapeHtml($_category->getName());
    } ?> <?php echo Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName() ?> to sell.
<?php endif;?>    
</section>
 	<div style="width:100%; height:50px; float:left;">
		<div style="float:left;">
		<?php if ($currentUrl = $this->helper('core/url')->getCurrentUrl()=='http://bumblebeewireless.com/preview/sell-my-ipod.html'):?>
<?php else :?>
<img src="<?php echo $this->getSkinUrl('images/questionmark.png')?>">
<?php endif;?>
		<!-- Place the following code in the head section of your web page -->
<!-- Place this code in the body section of your page -->
<span class="link"><a href="javascript: void(0)"><font style="color:#000; font-family:Helvetica; font-size:14px; position:relative; bottom:5px; width:100%;">
<?php $level = $this->getCurrentCategory()->getParentCategory()->getLevel();
if($level > 1){  ?>
<?php 
$shortname = Mage::getSingleton('catalog/layer')->getCurrentCategory()->getParentCategory()->getName();
$arr= str_word_count($shortname,1,'&àáãç0123456789');
if(in_array('iPhone',$arr)){
echo "What's my iPhone's capacity?";
}/*elseif (in_array('iPad',$arr)){
echo "What's my iPad's capacity?";
}*/ elseif (in_array('Blackberry',$arr)){
echo "What model Blackberry phone do I have?";
} elseif (in_array('HTC',$arr)){
echo "What model HTC phone do I have?";
} elseif (in_array('LG',$arr)){
echo "What model LG phone do I have?";
} elseif (in_array('Motorola',$arr)){
echo "What model Motorola phone do I have?";
} elseif (in_array('Nokia',$arr)){
echo "What model Nokia phone do I have?";
} elseif (in_array('Samsung',$arr)){
echo "What model Samsung phone do I have?";
}elseif (in_array('Kindle',$arr)){
echo "Which Kindle do I have?
";
}elseif (in_array('Galaxy',$arr)){
echo "Which version do I have?
";
}elseif (in_array('Nexus',$arr)){
echo "Which version do I have?
";
}
elseif (in_array('Surface',$arr)){
echo "Which version do I have?
";
}
elseif ($currentUrl = $this->helper('core/url')->getCurrentUrl()=='http://bumblebeewireless.com/preview/sell-my-ipad.html'){
echo "What's my iPad's capacity?
";
}
elseif ($currentUrl = $this->helper('core/url')->getCurrentUrl()=='http://bumblebeewireless.com/preview/sell-my-ipod.html'){
echo "";
}
else {
echo "Which model do I have?";
	}
							?>   
                           
<?php   // echo $this->getCurrentCategory()->getParentCategory()->getName();
    }
    else{
    echo $this->escapeHtml($_category->getName());
    } ?>  
</font>
<span>
<?php if ($currentUrl = $this->helper('core/url')->getCurrentUrl()=='http://bumblebeewireless.com/preview/sell-my-ipod.html'):?>
<?php else :?>
<img src="<?php echo $this->getSkinUrl('images/questionmark.png')?>">
<?php endif;?> &nbsp;<strong>
    <?php $level = $this->getCurrentCategory()->getParentCategory()->getLevel();
if($level > 1){  ?>
<?php 
							$shortname = Mage::getSingleton('catalog/layer')->getCurrentCategory()->getParentCategory()->getName();
							$arr= str_word_count($shortname,1,'&àáãç0123456789');
if(in_array('iPhone',$arr)){
echo "What's my iPhone's capacity?";
}/*elseif (in_array('iPad',$arr)){
echo "What's my iPad's capacity?";
} */elseif (in_array('Blackberry',$arr)){
echo "What model Blackberry phone do I have?";
} elseif (in_array('HTC',$arr)){
echo "What model HTC phone do I have?";
} elseif (in_array('LG',$arr)){
echo "What model LG phone do I have?";
} elseif (in_array('Motorola',$arr)){
echo "What model Motorola phone do I have?";
} elseif (in_array('Nokia',$arr)){
echo "What model Nokia phone do I have?";
} elseif (in_array('Samsung',$arr)){
echo "What model Samsung phone do I have?";
}elseif (in_array('Kindle',$arr)){
echo "Which Kindle do I have?
";
}elseif (in_array('Galaxy',$arr)){
echo "Which version do I have?
";
}
elseif (in_array('Nexus',$arr)){
echo "Which version do I have?
";
}
elseif (in_array('Surface',$arr)){
echo "Which version do I have?
";
}
elseif ($currentUrl = $this->helper('core/url')->getCurrentUrl()=='http://bumblebeewireless.com/preview/sell-my-ipad.html'){
echo "What's my iPad's capacity?
";
}
elseif ($currentUrl = $this->helper('core/url')->getCurrentUrl()=='http://bumblebeewireless.com/preview/sell-my-ipod.html'){
echo "";
}
else {
echo "Which model do I have?";
	}
							?>             
<?php   // echo $this->getCurrentCategory()->getParentCategory()->getName();
    }
    else{
    echo $this->escapeHtml($_category->getName());
    } ?>
    </strong><p style="height:3px;">&nbsp;</p><?php echo Mage::getSingleton('catalog/layer')->getCurrentCategory()->getDescription() ?></span></a></span>
		</div>
	</div>
<?php
$_categoriessub=$this->getCurrentChildCategories();
if($_categoriessub->count()):
$categorycount = 0;
foreach ($_categoriessub as $_categorysub):
if($_categorysub->getIsActive()):
$cur_categorysub=Mage::getModel('catalog/category')->load($_categorysub->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_categorysub);
$catName = $this->getCurrentCategory()->getName();
?>
	<div style="width:auto; height:auto; float:left; margin:0 10px 10px 0;">
		<div style="height: 175px; display: inline-block; line-height: 175px;">
		<?php /*?><a href="<?php echo $this->getCurrentCategory()->getUrl() ?>" <?php if ($this->isCategoryActive($cur_categorysub)): ?> class="active"<?php endif; ?> ><img src="<?php echo $this->getCurrentCategory()->getImageUrl() ?>" width="175" height="175" /></a><?php */?>
        <a href="<?php echo $this->getCurrentCategory()->getUrl() ?>" <?php if ($this->isCategoryActive($cur_categorysub)): ?> class="active"<?php endif; ?> ><img src="<?php echo $this->getCurrentCategory()->getImageUrl() ?>" width="175" style="vertical-align:middle;"/></a>
		</div>
		<div style="width:100%; max-width:185px; font-family:Helvetica; font-size:14px; color:#333333; text-align:center; height:30px;"> <?php echo $catName; ?></div>
		<br />
		<div><a href="<?php echo $this->getCurrentCategory()->getUrl() ?>"> <img src="<?php echo $this->getSkinUrl('close-div/images/offer.png')?>" /></a></div>
	</div>
<?php
endif;
endforeach;
endif;
?>		
 </div>