<script type="text/javascript" src="<?php echo $this->getSkinUrl('close-div/jquery.min.js')?>"></script>
<script type="text/javascript">
 function showonlytwo(thechosenone) {
     $('.newboxestwo').each(function(index) {
          if ($(this).attr("id") == thechosenone) {
               $(this).show(200);
          }
          else {
               $(this).hide(200);
          }
     });
}
</script>
<style type="text/css">

span.link {
    	position: relative;
}

    span.link a span {
    	display: none;
		font: 12px "Arial",sans-serif !important;
}

span.link a:hover {
    	font-size: 99%;
    	font-color: #000000;
}

span.link a:hover span { 
   display: block;
position: absolute;
margin-top: 0px;
margin: 0px;
width: 265px;
padding: 15px;
z-index: 100;
color: #494949;
background: none repeat scroll 0% 0% #fff;
font: 12px "Arial",sans-serif;
text-align: left;
text-decoration: none;
border: 2px solid #FCE63C;
border-radius: 5px;
}
span.link a:hover span strong{
	font-size:12px;
}
span.link a:hover span img{
	vertical-align:middle;
}
#selectdevice {display:block; float:left; font-size:20px; margin:10px 0; color:333333;}
</style>
<style>
.list
{
width:1050px; height:100%; margin:0px;
}
.list div a img
{
 transition: opacity .5s;
-moz-transition: opacity .5s; /* Firefox 4 */
-webkit-transition: opacity .5s; /* Safari and Chrome */
-o-transition: opacity .5s; /* Opera */

}
.list:hover div a img
{
opacity:0.5; 
}

.list div a img:hover
{transition: opacity .5s;
-moz-transition: opacity .5s; /* Firefox 4 */
-webkit-transition: opacity .5s; /* Safari and Chrome */
-o-transition: opacity .5s; /* Opera */

}
.list div a img:hover{opacity:1;}
.list div a.active{opacity:1 !important;}
#subcateswitcher {margin:0px; padding:0px; padding-right:20px; float:left; text-align:center; font-weight:bold; color:#4C4C4C;}
.selected { font: bold 12px Arial, Helvetica, sans-serif; color:#FF0000; transition: opacity 1;
-moz-transition: opacity 1; /* Firefox 4 */
-webkit-transition: opacity 1; /* Safari and Chrome */
-o-transition: opacity 1; /* Opera */}
</style>
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script>
$(function () {
$(".somelink a").click(function (e) {
e.preventDefault();
$(".somelink a").addClass("active").not(this).removeClass("active");
});
});
</script>
<div style="width:100%; display:block; margin:0px; float:left;">
 
		<div style="float:left;">
		<!-- Place the following code in the head section of your web page -->



<!-- Place this code in the body section of your page -->
<span class="link"><a href="javascript: void(0)">
<?php if (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName()=='Cell Phones'):?>
<font style="color:#000; font-family:Helvetica; font-size:14px; position:relative; width:100%; display:block; margin-bottom:10px;">
Which Brand Do I Have? </font>
<?php elseif (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName()=='Tablets'):?>
<font style="color:#000; font-family:Helvetica; font-size:14px; position:relative; width:100%; display:block; margin-bottom:10px;">
Which Brand Do I Have? </font>
<?php elseif (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName()=='Apple Computers'):?>
<font style="color:#000; font-family:Helvetica; font-size:14px; position:relative; width:100%; display:block; margin-bottom:10px;">
Which Brand Do I Have? </font>
<?php elseif (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName()=='iPads'):?>
<font style="color:#000; font-family:Helvetica; font-size:14px; position:relative; width:100%; display:block; margin-bottom:10px;">
Which iPad Do I Have? </font>
<?php elseif (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName()=='iPods'):?>
<font style="color:#000; font-family:Helvetica; font-size:14px; position:relative; width:100%; display:block; margin-bottom:10px;">
Which iPod Do I Have? </font>
<?php else :?>
<font style="color:#000; font-family:Helvetica; font-size:14px; position:relative; width:100%;">
Which Model Do I Have? </font>
<?php endif;?>   
<?php if (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getDescription()!=''):?>


<span><img src="<?php echo $this->getSkinUrl('images/questionmark.png')?>"> &nbsp;<strong>Which <?php if (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName()=='Cell Phones'):?>
Brand
<?php elseif (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName()=='Tablets'):?>
Brand
<?php elseif (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName()=='Apple Computers'):?>
Brand
<?php elseif (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName()=='iPads'):?>
iPad
<?php elseif (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName()=='iPods'):?>
iPod
<?php else :?>
Model
<?php endif;?> Do I Have?</strong><p style="height:3px;">&nbsp;</p><?php echo Mage::getSingleton('catalog/layer')->getCurrentCategory()->getDescription() ?></span>


<?php endif;?>
</a></span>
		</div>

	</div>
<div class="list" style=" float:left;">
<table width="100%" height="">
<tr>
<td style="vertical-align:top; float:left;">
 <?php
$_subcategories=$this->getCurrentChildCategories();
if($_subcategories->count()):
$categorycount = 0;
$third=500;
foreach ($_subcategories as $_subcategory):
if($_subcategory->getIsActive()):
$cur_category2nd=Mage::getModel('catalog/category')->load($_subcategory->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_category2nd);
$catName = $this->getCurrentCategory()->getName();
$third++;
?>
         <div style="padding: 5px;  color:#4C4C4C; font-family:Helvetica; font-size:12px; font-weight:bold;  text-align:center; float:left; ">
         <script language="JavaScript" type="text/javascript">
/*<![CDATA[*/
var Lst;

function CngClass(obj){
 if (Lst) Lst.className='';
 obj.className='selected';
 Lst=obj;
}

/*]]>*/
</script>
            <a onclick="CngClass(this);"  id="myHeader1" href="javascript:showonlytwo('newboxestwo<?php echo $third;?>');" <?php if ($this->isCategoryActive($_subcategory)): ?> class="active"<?php endif; ?> >
			
				<img src="<?php echo $this->getCurrentCategory()->getImageUrl() ?>"  onclick="document.getElementById('p<?php echo $third;?>').style.display='none'"   /><br><?php echo $this->getCurrentCategory()->getName() ?></a>
                <?php /*?><?php $displayMode = $this->getCurrentCategory()->getDisplayMode();?>
				<?php if($displayMode == 'PAGE'):?>
   Static block <?php echo $this->getCurrentCategory()->getName() ?>
<?php else: ?>
   				<?php echo $this->getCurrentCategory()->getName() ?>

<?php endif; ?><?php */?>

         </div>
		 
	<?php
endif;
endforeach;
endif;
?>	
<?php
$_subcategories=$this->getCurrentChildCategories();
if($_subcategories->count()):
$categorycount = 0;
$third=500;
foreach ($_subcategories as $_subcategory):
if($_subcategory->getIsActive()):
$cur_category2nd=Mage::getModel('catalog/category')->load($_subcategory->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_category2nd);
$catName = $this->getCurrentCategory()->getName();
$third++;
?>		 
 <div class="newboxestwo" id="newboxestwo<?php echo $third;?>" style=" display: none;padding: 5px; margin-top:0px; width: 1024px;  z-index:1111;"> 
 <div style="width:1024px;">		
<?php $displayMode = $this->getCurrentCategory()->getDisplayMode();?>
<?php if($displayMode == 'PAGE'):?>  
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sellit_fourthlevel_listing')->toHtml(); ?>
<?php else: ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sellit_eigthlevel_listing')->toHtml(); ?>
<?php endif; ?>
</div> 
</div>
<?php
endif;
endforeach;
endif;
?>	
</td>
 </tr>
 </table>
 </div>