<script type="text/javascript" src="<?php echo $this->getSkinUrl('close-div/jquery.min.js')?>"></script>

<script type="text/javascript">

 function showonlysix(thechosenfive) {

     $('.newboxessixth').each(function(index) {

          if ($(this).attr("id") == thechosenfive) {

               $(this).show(200);

          }

          else {

               $(this).hide(200);

          }

     });

}

</script>
<div class="list" style=" float:left;">

<table width="100%" height="">
<tr>

<td style="vertical-align:top; float:left;">

 
 <?php
$_subcategories=$this->getCurrentChildCategories();
if($_subcategories->count()):
$categorycount = 0;
$fourth=1000;
foreach ($_subcategories as $_subcategory):
if($_subcategory->getIsActive()):
$cur_category5th=Mage::getModel('catalog/category')->load($_subcategory->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_category5th);
$catName = $this->getCurrentCategory()->getName();
$fourth++;
?>
 
 
 
         <div style="padding: 5px;  color:#4C4C4C; font-family:Helvetica; font-size:12px; font-weight:bold;  text-align:center; float:left; ">
            <a id="t5" onclick="T5.CngClass(this);"  href="javascript:showonlysix('newboxessixth<?php echo $fourth;?>');" <?php if ($this->isCategoryActive($_subcategory)): ?> class="active"<?php endif; ?> >
				<?php if (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getImageUrl()!=''):?>
				<img src="<?php echo $this->getCurrentCategory()->getImageUrl() ?>"  onclick="document.getElementById('p<?php echo $fourth;?>').style.display='none'"   /><br><?php echo $this->getCurrentCategory()->getName() ?>
				<?php else:?>
                <?php echo $this->getCurrentCategory()->getName() ?>
                <?php endif;?>
			</a>
         </div>
		 
	<?php
endif;
endforeach;
endif;
?>	
		 
		 
<?php
$_subcategories=$this->getCurrentChildCategories();
if($_subcategories->count()):
$categorycount = 0;
$fourth=1000;
foreach ($_subcategories as $_subcategory):
if($_subcategory->getIsActive()):
$cur_category5th=Mage::getModel('catalog/category')->load($_subcategory->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_category5th);
$catName = $this->getCurrentCategory()->getName();
$fourth++;
?>		 
		 
         <div class="newboxessixth" id="newboxessixth<?php echo $fourth;?>" style=" display: none;padding: 5px; margin-top:0px; width: 1024px;  z-index:1111;"> 
 <div style="width:1024px;">		

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sellit_eigthlevel_listing')->toHtml(); ?>

</div> 

</div>
  
<?php
endif;
endforeach;
endif;
?>	


 
 </td>

  

 </tr>
 </table>
 </div>