<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head')?>
</head>
<body>
<section id="main_container">
	<section id="contaner"><span>Bumblebee Wireless'' Leaders in Buying, Selling, Repairing and Customizing Handheld Electronics. | Click - Ship - Fix - Return</span>
    <section class="top_link">
    	<ul>
       <li><a href="<?php echo $this->getUrl('customer/account/login')?>">Log In</a></li>
        <li><a href="<?php echo $this->getUrl('checkout')?>">Checkout</a></li>
        <li><a href="<?php echo $this->getUrl('checkout/cart')?>">My Cart</a></li>
        <li><a href="<?php echo $this->getUrl('customer/account/')?>">My Account</a></li>
        </ul></section></section></section>
        <section id="center_main_container">
        <section id="center_container">
        <?php echo $this->getChildHtml('header')?>
<span class="clear"></span>
<section id="banner_container">
</section>
<section id="center_mid_container">
	<section id="category_container">
                    	<!--<section class="category_heading"> <?php echo Mage::getSingleton('cms/page')->getTitle() ?></section>
                         <section class="categorysub_heading">Click on your Manufacture Below</section>-->
                        <section id="categorylist-container">
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('global_messages') ?>
<?php echo $this->getChildHtml('content') ?>   
        </section>
</section>
</section>
<?php echo $this->getChildHtml('footer')?></section></section>
</body>
</html>