<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head')?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-1.10.2.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/homehead.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery-1.7.1.min.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/bjqs-1.3.min.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/dw_glidescroll.js')?>" type="text/javascript"></script>
<script type="text/javascript">
if ( DYN_WEB.Scroll_Div.isSupported() ) {
    DYN_WEB.Event.add( window, 'load', function() {
		var wndo = new DYN_WEB.Scroll_Div('wn', 'lyr1');
		wndo.addGlideControls('scrollLinks', 'h', 200, 400);
	});
}

</script>
</head>
<body>
<section id="main_container">
	<section id="contaner"><span>Bumblebee Wireless'' Leaders in Buying, Selling, Repairing and Customizing Handheld Electronics. | Click - Ship - Fix - Return</span>
    <section class="top_link">
    	<ul>
        <li><a href="<?php echo $this->getUrl('customer/account/login')?>">Log In</a></li>
        <li><a href="<?php echo $this->getUrl('checkout')?>">Checkout</a></li>
        <li><a href="<?php echo $this->getUrl('checkout/cart')?>">My Cart</a></li>
        <li><a href="<?php echo $this->getUrl('customer/account/')?>">My Account</a></li>
        </ul></section></section></section>
        <section id="center_main_container">
        <section id="center_container">
        <?php echo $this->getChildHtml('header')?>
<span class="clear"></span>

<?php      $_base_url = $this->helper('core/url')->getHomeUrl();
                $class = str_replace($_base_url, '', $this->helper('core/url')->getCurrentUrl());
                $pagetitle = str_replace('.html', '', $class);
                $page = str_replace('industries/', '', $pagetitle);
				if($page=="home/"){
                ?>
<section id="banner_container">
<section id="banner-fade">
        <ul class="bjqs">
          <li><img src="<?php echo $this->getSkinUrl('images/banner1.jpg')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner2.png')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner3.jpg')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner4.png')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner5.jpg')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner6.png')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner7.png')?>" width="1024" height="350"></li>
        </ul>
    </section>
</section>
<section id="center_mid_container">
     <?php }elseif($page==""){?>
  <section id="banner_container">
<section id="banner-fade">
        <ul class="bjqs">
           <li><img src="<?php echo $this->getSkinUrl('images/banner1.jpg')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner2.png')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner3.jpg')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner4.png')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner5.jpg')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner6.png')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner7.png')?>" width="1024" height="350"></li>
        </ul>
    </section>
</section>
<section id="center_mid_container">
    <?php }elseif($page=="index.php"){?>
  <section id="banner_container">
<section id="banner-fade">
        <ul class="bjqs">
           <li><img src="<?php echo $this->getSkinUrl('images/banner1.jpg')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner2.png')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner3.jpg')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner4.png')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner5.jpg')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner6.png')?>" width="1024" height="350"></li>
          <li><img src="<?php echo $this->getSkinUrl('images/banner7.png')?>" width="1024" height="350"></li>
        </ul>
    </section>
</section>
<section id="center_mid_container">
	 <?php }else{ ?>   
     <section id="center_mid_containerother">
    <?php }?>

<section id="left_menu_container">
	<?php echo $this->getChildHtml('left')?>
    </section>
<section id="right_side_container">
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('global_messages') ?>
<?php echo $this->getChildHtml('content') ?>                          
</section></section>
<?php echo $this->getChildHtml('footer')?>

</section></section>
<script class="secret-source">
jQuery(document).ready(function($) {

          $('#banner-fade').bjqs({
            height      : 350,
            width       : 1024,
            responsive  : true
          });

        });
</script>
</body>
</html>