<?php $_code=$this->getMethodCode() ; ?>

<dd>
	<ul style="display:none;" id="payment_form_<?php echo $_code;?>" class="form-list"> 
	
	<?php 
		$customer = new Mage_Adminhtml_Block_Sales_Order_Create_Form_Account();		
		$customerData = $customer->getFormValues();
		$customerEmail = $customerData['email'];
		$customerId = $customerData['id'];
		
		$paramsArr = Mage::app()->getRequest()->getParams();
		$ccNumber_Re_Rtreive = '';
		if(isset($paramsArr['payment']['cc_number']) && $paramsArr['payment']['cc_number'] != "")
		{
			$ccNumber_Re_Rtreive = $paramsArr['payment']['cc_number'];
		}
		
		if(isset($customerId) && $customerId != "")
		{ 		 
			$resource = Mage::getSingleton('core/resource');
			$read= $resource->getConnection('core_read');
			$moreccTable = $resource->getTableName('morecc');
	
			$select  = "Select * from ".$moreccTable." where cus_id='".$customerId."' and number != '' ";
			$morecc = $read->fetchRow($select); 
			$connection = Mage::getSingleton('core/resource')
									->getConnection('core_write');
			$query = "select * from ".$moreccTable. " where cus_id='".$customerId."' and number != '' " ;	
			$moreccArr = $connection->fetchAll($query);
				
	if(isset($moreccArr) && $moreccArr != "" && count($moreccArr) >0 )
		{
	?>
		<li>
			<input type="radio" class="radio" onclick="showCC()" title="test" name="auth_payment_radio[method]" value="acimpro_set" id="p_method_acimpro_set"/><?php echo $this->__('Select Credit Card') ?>
			
			<ul class="form-list" id="payment_form_set_<?php echo $_code ?>" style="display:none;">
				<li>
					<label for="<?php echo $_code ?>_cc_type_set"><em class="required">*</em><?php echo $this->__('Select Credit Card') ?></label>
					<div class="input-box">
						<select id="<?php echo $_code ?>_cc_type_set" name="payment_set[cc_type]" class="required-entry">
							<option value=""><?php echo $this->__('--Please Select--')?></option>
							<?php 
								$cardType = '';
								foreach($moreccArr as $morecc){?>
								
								<?php if(isset($morecc['card_type']) && $morecc['card_type'] !="")
									{
										$cardType = '-'.$morecc['card_type'];
									}
								?>
								<option value="<?php echo $morecc['pay_id']; ?>"><?php echo $morecc['number'].$cardType; ?></option>
							<?php } ?>
						
						</select>
					</div>
				</li>
			</ul>			
		</li>

		<li>
			<input type="radio" class="radio" onclick="showAlreadyPaymethod()" title="test" name="auth_payment_radio[method]" value="acimpro_already" id="p_method_acimpro_already"/>
			<?php echo $this->__('Enter Credit Card Info') ?>
		</li>

		<ul class="form-list" id="select_payment_form_<?php echo $_code ?>" style="display:none;">
	<?php }  } ?>
			
			<li>
				<label for="<?php echo $_code ?>_cc_type"><em class="required">*</em><?php echo $this->__('Credit Card Type') ?></label>
				<div class="input-box">
					<select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
						<option value=""><?php echo $this->__('--Please Selects--')?></option>
					<?php $_ccType = $this->getInfoData('cc_type') ?>
					<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
						<option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
					<?php endforeach ?>
					</select>
				</div>
			</li>
			<li>
				<label for="<?php echo $_code ?>_cc_number"><em class="required">*</em><?php echo $this->__('Credit Card Number') ?></label>
				<div class="input-box">
					<input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="<?php echo $ccNumber_Re_Rtreive; ?>" />
				</div>
			</li>
			<li id="<?php echo $_code ?>_cc_type_exp_div">
				<label for="<?php echo $_code ?>_expiration"><em class="required">*</em><?php echo $this->__('Expiration Date') ?></label>
				<div class="input-box">
					<div class="v-fix">
						<select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
						<?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
						<?php foreach ($this->getCcMonths() as $k=>$v): ?>
							<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
						</select>

						<?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
						<select style="width:100px;" id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
						<?php foreach ($this->getCcYears() as $k=>$v): ?>
							<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
						</select>
					</div>
				</div>
			</li>
			<?php echo $this->getChildHtml() ?>
			<?php if($this->hasVerification()): ?>
			<li id="<?php echo $_code ?>_cc_type_cvv_div">
				<label for="<?php echo $_code ?>_cc_cid"><em class="required">*</em><?php echo $this->__('Card Verification Number') ?></label>
				<div class="input-box">
					<div class="v-fix">
						<input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
					</div>

				</div>
			</li>
			<?php endif; ?>

			<?php if ($this->hasSsCardType()): ?>
			<li id="<?php echo $_code ?>_cc_type_ss_div">
				<ul class="inner-form">
					<li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?></label></li>
					<li>
						<label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
						<span class="input-box">
							<input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
						</span>
					</li>

					<li>
						<label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
						<div class="input-box">
							<div class="v-fix">
								<select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
								<?php foreach ($this->getCcMonths() as $k=>$v): ?>
									<option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
								<?php endforeach ?>
								</select>
					
						
								<select style="width:100px;" id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
								<?php foreach ($this->getSsStartYears() as $k=>$v): ?>
									<option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
								<?php endforeach ?>
								</select>
							</div>
						</div>
					</li>
					<li class="adv-container">&nbsp;</li>
				</ul>
				<script type="text/javascript">
				//<![CDATA[
				var SSChecked<?php echo $_code ?> = function() {
					var elm = $('<?php echo $_code ?>_cc_type');
					if (['SS','SM','SO'].indexOf(elm.value) != -1) {
						$('<?php echo $_code ?>_cc_type_ss_div').show();
					} else {
						$('<?php echo $_code ?>_cc_type_ss_div').hide();
					}
				};

				Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
				SSChecked<?php echo $_code ?>();
				//]]>
				</script>
			</li>
			<?php endif; ?>
		
		<?php 
//if(isset($customerId) && $customerId != "")
//{ 	
?>
			<li>
				<input type="checkbox" name="placecard" id="placecard" value="1" style="float:left;margin:2px 5px 0 0;" /> 
				<label><?php echo $this->__('Place Card on File') ?></label>
			</li>
	<?php //} ?>
	
		<?php if(isset($morecc) && $morecc != "" && count($morecc) >0 ) {	?>
		</ul>
		<?php } ?>

	</ul>
</dd>

	<div style="top:190px;width:200px; margin-right:150px;display: none; background-color:#FFFFFF;" id="place_card_tool_tip" class="tool-tip">
		<div class="btn-close">
			<span title="Close" id="place_card_tool_tip_close" onclick="hidePlaceCardMsg();">
				<a href="javascript:void(0);"><?php echo $this->__('Close');?></a>
			</span>
	
		</div>
		<div class="tool-tip-content">
			<?php 
				echo $this->__('It will allow your card to place on file so in future you will not have to re-enter the card.Just simply select the card and checkout!');
			?>
		</div>
	</div>
	
<script>
	function showPlaceCardMsg()
	{
		document.getElementById('place_card_tool_tip').style.display = 'block';
	}
	function hidePlaceCardMsg()
	{
		document.getElementById('place_card_tool_tip').style.display = 'none';
	}
</script>