<script type="text/javascript" src="<?php echo $this->getSkinUrl('close-div/jquery.min.js')?>"></script>

<script type="text/javascript">

 function showonlyone(thechosenone) {

     $('.newboxes').each(function(index) {

          if ($(this).attr("id") == thechosenone) {

               $(this).show(200);

          }

          else {

               $(this).hide(200);

          }

     });

}

</script>
<style type="text/css">

span.link {
    	position: relative;
}

    span.link a span {
    	display: none;
		font: 12px "Arial",sans-serif !important;
}

span.link a:hover {
    	font-size: 99%;
    	font-color: #000000;
}

span.link a:hover span { 
   display: block;
position: absolute;
margin-top: 0px;
margin: 0px;
width: 265px;
padding: 15px;
z-index: 100;
color: #494949;
background: none repeat scroll 0% 0% #fff;
font: 12px "Arial",sans-serif;
text-align: left;
text-decoration: none;
border: 2px solid #FCE63C;
border-radius: 5px;
}
span.link a:hover span strong{
	font-size:12px;
}
span.link a:hover span img{
	vertical-align:middle;
}
#selectdevice {display:block; float:left; font-size:20px; margin:10px 0; color:333333;}
</style>
<style>
.list
{
width:1050px; height:100%; margin:0px;
}
.list div a img
{
 transition: opacity .5s;
-moz-transition: opacity .5s; /* Firefox 4 */
-webkit-transition: opacity .5s; /* Safari and Chrome */
-o-transition: opacity .5s; /* Opera */

}
.list:hover div a img
{
opacity:0.5; 
}

.list div a img:hover
{transition: opacity .5s;
-moz-transition: opacity .5s; /* Firefox 4 */
-webkit-transition: opacity .5s; /* Safari and Chrome */
-o-transition: opacity .5s; /* Opera */

}
.list div a img:hover{opacity:1;}
.list div a.active{opacity:1 !important;}
#subcateswitcher {margin:0px; padding:0px; padding-right:20px; float:left; text-align:center; font-weight:bold; color:#4C4C4C;}

</style>
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script>
$(function () {
$(".somelink a").click(function (e) {
e.preventDefault();
$(".somelink a").addClass("active").not(this).removeClass("active");
});
});
</script>
<div style="width:100%; display:block; margin:0px; float:left;">
 
		<div style="float:left;">
		<!-- Place the following code in the head section of your web page -->



<!-- Place this code in the body section of your page -->
<span class="link"><a href="javascript: void(0)"><font style="color:#000; font-family:Helvetica; font-size:14px; position:relative; width:100%;">which model do i have ?  </font>
<?php if (Mage::getSingleton('catalog/layer')->getCurrentCategory()->getDescription()!=''):?>
<span><img src="<?php echo $this->getSkinUrl('images/questionmark.png')?>"> &nbsp;<strong>Which model do i have ?</strong><p style="height:3px;">&nbsp;</p><?php echo Mage::getSingleton('catalog/layer')->getCurrentCategory()->getDescription() ?></span>
<?php endif;?>
</a></span>
		</div>

	</div>
<div class="list" style=" float:left;">

     <table width="100%" height="">

<tr>

 

<td style="vertical-align:top; float:left;">

 
<?php
$_categories=$this->getCurrentChildCategories();
if($_categories->count()):
$categorycount = 0;
$cms=0;
foreach ($_categories as $_category):
if($_category->getIsActive()):
$cur_category=Mage::getModel('catalog/category')->load($_category->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_category);
$catName = $this->getCurrentCategory()->getName();
$cms++;

?>
         <div id="subcateswitcher">

            <a id="myHeader1" href="javascript:showonlyone('newboxes<?php echo $cms;?>');" >

			

				<img src="<?php echo $this->getCurrentCategory()->getImageUrl() ?>" style="margin:0px; padding:0px; " onClick="document.getElementById('p<?php echo $cms;?>').style.display='none'"  /><br><?php echo $this->getCurrentCategory()->getName() ?>

				

			</a>

         </div>


<?php
endif;
endforeach;
endif;
?>		 

		 <?php
$_categories=$this->getCurrentChildCategories();
if($_categories->count()):
$categorycount = 0;
$cms=0;
foreach ($_categories as $_category):
if($_category->getIsActive()):
$cur_category=Mage::getModel('catalog/category')->load($_category->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_category);
$catName = $this->getCurrentCategory()->getName();
$cms++;
?>
        
<div class="newboxes" id="newboxes<?php echo $cms;?>" style="  display: none;  margin-top:0px; max-width: 1024px; width:100%; max-height:1100px; z-index:1111; "> 

  <div style="max-width:1000px; width:100%; height:100%; padding: 0px; margin:0px; ">		

<div style="width:100%; height:100%; padding: 0px; margin:0px; float:left; ">

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sellit_thirdlevel_listing')->toHtml(); ?>


 </div>

</div> 



</div>

<?php
endif;
endforeach;
endif;
?>		 

         

      

	    

 

 </td>



  



 </tr>

 </table>               
                    
            </div>