<div style="width:100%; height:100%; padding: 0px; margin:0px; float:left; ">
<section id="selectdevice">Select your <?php echo Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName() ?> to sell.</section>

 	<div style="width:100%; height:50px; float:left;">
 
		<div style="float:left;">

		<img src="<?php echo $this->getSkinUrl('close-div/images/question.png')?>" />

		<!-- Place the following code in the head section of your web page -->



<!-- Place this code in the body section of your page -->
<span class="link"><a href="javascript: void(0)"><font style="color:#000; font-family:Helvetica; font-size:14px; position:relative; bottom:5px; width:100%;">What's my <?php echo Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName() ?> capacity ?  </font><span><img src="<?php echo $this->getSkinUrl('images/questionmark.png')?>"> &nbsp;<strong>What's my <?php echo Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName() ?> capacity ?</strong><p style="height:3px;">&nbsp;</p><?php echo Mage::getSingleton('catalog/layer')->getCurrentCategory()->getDescription() ?></span></a></span>





		</div>

	</div>


<?php
$_categoriessub=$this->getCurrentChildCategories();
if($_categoriessub->count()):
$categorycount = 0;
foreach ($_categoriessub as $_categorysub):
if($_categorysub->getIsActive()):
$cur_categorysub=Mage::getModel('catalog/category')->load($_categorysub->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_categorysub);
$catName = $this->getCurrentCategory()->getName();
?>
	

	

	<div style="width:auto; height:auto; float:left; margin-right:10px;">

		<div>

		<a href="<?php echo $this->getCurrentCategory()->getUrl() ?>" <?php if ($this->isCategoryActive($cur_categorysub)): ?> class="active"<?php endif; ?> ><img src="<?php echo $this->getCurrentCategory()->getImageUrl() ?>" width="175" height="175" /></a>

		</div>

		<div style="width:100%; max-width:225px; font-family:Helvetica; font-size:14px; color:#333333;"> <?php echo $catName; ?></div>

		<br />

		<div><a href="<?php echo $this->getCurrentCategory()->getUrl() ?>"> <img src="<?php echo $this->getSkinUrl('close-div/images/offer.png')?>" /></a></div>

	</div>
    
    
<?php
endif;
endforeach;
endif;
?>		
    
    
    
    

 </div>