<?php
$_categories     = $this->getCategories();
$_collectionSize = count($_categories);

if (!$_collectionSize) :
    return;
endif;

$columnsCount = $this->getColumnCount();
$showImage    = $this->getShowImage();
$height       = $this->getImageHeight();
$width        = $this->getImageWidth();
$maxCategoryCount    = $this->getCategoryCount();
$maxSubcategoryCount = $this->getSubcategoryCount();
$i = 0;
?>

<section id="category-listing">
<ul>
<?php foreach ($_categories as $_category) : ?>

    <?php if ($i >= $maxCategoryCount): break; endif; ?>

  
    <li>
        
        <?php if ($showImage) : ?>
        <?php if ($_category->getId()=='1262'):?>
            <a href="http://bumblebeewireless.com/preview/apple-ipad-repair.html" title="<?php echo $this->htmlEscape($_category->getName()) ?>" class="product-image">
                <?php if(!$resizeImage = $this->getResizeImage()): ?>
                    <?php
                        $style = '';
                        if (!empty($width)):
                            $style = 'width: ' . (is_numeric($width) ? $width . 'px' : $width);
                        elseif (!empty($height)):
                            $style = 'height: ' . (is_numeric($height) ? $height . 'px' : $height);
                        endif;
                    ?>
                    <img src="<?php echo $this->getImage($_category) ?>" style="<?php echo $style ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
                <?php else: ?>
                    <img src="<?php echo Mage::helper('easycatalogimg/image')->resize($this->getImage($_category), $width, $height) ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" /><br/><span><?php echo $this->htmlEscape($_category->getName()) ?></span>
                <?php endif; ?>
            </a>
            <?php elseif ($_category->getId()=='57'):?>
            <a href="http://bumblebeewireless.com/preview/apple-iphone-repair.html" title="<?php echo $this->htmlEscape($_category->getName()) ?>" class="product-image">
                <?php if(!$resizeImage = $this->getResizeImage()): ?>
                    <?php
                        $style = '';
                        if (!empty($width)):
                            $style = 'width: ' . (is_numeric($width) ? $width . 'px' : $width);
                        elseif (!empty($height)):
                            $style = 'height: ' . (is_numeric($height) ? $height . 'px' : $height);
                        endif;
                    ?>
                    <img src="<?php echo $this->getImage($_category) ?>" style="<?php echo $style ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
                <?php else: ?>
                    <img src="<?php echo Mage::helper('easycatalogimg/image')->resize($this->getImage($_category), $width, $height) ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" /><br/><span><?php echo $this->htmlEscape($_category->getName()) ?></span>
                <?php endif; ?>
            </a>
            <?php else :?>
            <a href="<?php echo $_category->getUrl()?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>" class="product-image">
                <?php if(!$resizeImage = $this->getResizeImage()): ?>
                    <?php
                        $style = '';
                        if (!empty($width)):
                            $style = 'width: ' . (is_numeric($width) ? $width . 'px' : $width);
                        elseif (!empty($height)):
                            $style = 'height: ' . (is_numeric($height) ? $height . 'px' : $height);
                        endif;
                    ?>
                    <img src="<?php echo $this->getImage($_category) ?>" style="<?php echo $style ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
                <?php else: ?>
                    <img src="<?php echo Mage::helper('easycatalogimg/image')->resize($this->getImage($_category), $width, $height) ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" /><br/><span><?php echo $this->htmlEscape($_category->getName()) ?></span>
                <?php endif; ?>
            </a>
              <?php endif; ?>
        <?php endif; ?>
       
    </li>

   

<?php endforeach; ?>
<?php 
//$estore_current_category = Mage::registry('current_category');
$estore_parent_id = $_category->parent_id; ?>
<?php if ($estore_parent_id==6):?>
        <li><a href="<?php echo $this->getUrl('iphone-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
        <?php elseif ($estore_parent_id==8):?>
         <li><a href="<?php echo $this->getUrl('ipod-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==9):?>
         <li><a href="<?php echo $this->getUrl('ipad-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
          <?php elseif ($estore_parent_id==1222):?>
         <li><a href="<?php echo $this->getUrl('mac-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==57):?>
         <li><a href="<?php echo $this->getUrl('iphone-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==55):?>
         <li><a href="<?php echo $this->getUrl('samsung-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==53):?>
         <li><a href="<?php echo $this->getUrl('htc-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==1090):?>
         <li><a href="<?php echo $this->getUrl('blackberry-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==189):?>
         <li><a href="<?php echo $this->getUrl('amazon-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==194):?>
         <li><a href="<?php echo $this->getUrl('sony-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==1266):?>
         <li><a href="<?php echo $this->getUrl('kindle-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==1268):?>
         <li><a href="<?php echo $this->getUrl('nook-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partimages.jpg')?>" height="183"></a></br><span>What model do i have? </span></a></li>
      <?php endif; ?> 
</ul>
</section>

<script type="text/javascript">decorateGeneric($$('ul.category-grid'), ['odd','even','first','last'])</script>
