<?php
$_categories     = $this->getCategories();
$_collectionSize = count($_categories);

if (!$_collectionSize) :
    return;
endif;

$columnsCount = $this->getColumnCount();
$showImage    = $this->getShowImage();
$height       = $this->getImageHeight();
$width        = $this->getImageWidth();
$maxCategoryCount    = $this->getCategoryCount();
$maxSubcategoryCount = $this->getSubcategoryCount();
$i = 0;
?>

<section id="category-listing">
<ul>
<?php 
foreach ($_categories as $_category);
//$estore_current_category = Mage::registry('current_category');
$estore_parent_id = $_category->parent_id; ?>
<?php if ($estore_parent_id==6):?>
        <li><a href="<?php echo $this->getUrl('identify-my-iphone-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatiphonemodel.png')?>" height="183"></a></br><span>What Model Do I Have? </span></a></li>
        <?php elseif ($estore_parent_id==8):?>
         <li><a href="<?php echo $this->getUrl('identify-my-ipod-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatipodmodel.png')?>" height="183"></a></br><span>What Model Do I Have? </span></a></li>
         <?php elseif ($estore_parent_id==9):?>
         <li><a href="<?php echo $this->getUrl('identify-my-ipad-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/ipadwhatmodelimage.png')?>" height="183"></a></br><span>What Model Do I Have? </span></a></li>
          <?php elseif ($estore_parent_id==1222):?>
         <li><a href="<?php echo $this->getUrl('identify-my-apple-laptop-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatmodelmacbook.png')?>" height="183"></a></br><span>What Model Do I Have? </span></a></li>
         <?php elseif ($estore_parent_id==55):?>
         <li><a href="<?php echo $this->getUrl('identify-my-samsung-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatmodelsamsung.png')?>" height="183"></a></br><span>What Model Do I Have? </span></a></li>
        <?php elseif ($estore_parent_id==22):?>
         <li><a href="<?php echo $this->getUrl('identify-my-laptop-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatmodelmacbook.png')?>" height="183"></a></br><span>What Model Do I Have? </span></a></li>
         <?php elseif ($estore_parent_id==57):?>
         <li><a href="<?php echo $this->getUrl('identify-my-iphone-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatiphonemodel.png')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==191):?>
         <li><a href="<?php echo $this->getUrl('identify-my-lg-phone-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatmodelsamsung.png')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==53):?>
         <li><a href="<?php echo $this->getUrl('identify-my-htc-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatmodelsamsung.png')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==1090):?>
         <li><a href="<?php echo $this->getUrl('identify-my-blackberry-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatmodelsamsung.png')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==193):?>
         <li><a href="<?php echo $this->getUrl('identify-my-nokia-phone-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatmodelsamsung.png')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==54):?>
         <li><a href="<?php echo $this->getUrl('identify-my-motorola-phone-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatmodelsamsung.png')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==189):?>
         <li><a href="<?php echo $this->getUrl('identify-my-amazon-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatmodelsamsung.png')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==194):?>
         <li><a href="<?php echo $this->getUrl('identify-my-sony-phone-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatmodelsamsung.png')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         <?php elseif ($estore_parent_id==199):?>
         <li><a href="<?php echo $this->getUrl('identify-my-zte-model')?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/whatmodelsamsung.png')?>" height="183"></a></br><span>What model do i have? </span></a></li>
         
      <?php endif; ?> 
      
<?php foreach ($_categories as $_category) : ?>

    <?php if ($i >= $maxCategoryCount): break; endif; ?>

  
    <li>
        
        <?php if ($showImage) : ?>
        <?php if ($_category->getId()=='1262'):?>
            <a href="<?php echo $this->getUrl('apple-ipad-repair.html')?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>" class="product-image">
                <?php if(!$resizeImage = $this->getResizeImage()): ?>
                    <?php
                        $style = '';
                        if (!empty($width)):
                            $style = 'width: ' . (is_numeric($width) ? $width . 'px' : $width);
                        elseif (!empty($height)):
                            $style = 'height: ' . (is_numeric($height) ? $height . 'px' : $height);
                        endif;
                    ?>
                    <img src="<?php echo $this->getImage($_category) ?>" style="<?php echo $style ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
                <?php else: ?>
                    <img src="<?php echo Mage::helper('easycatalogimg/image')->resize($this->getImage($_category), $width, $height) ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" /><br/><span><?php echo $this->htmlEscape($_category->getName()) ?></span>
                <?php endif; ?>
            </a>
            <?php elseif ($_category->getId()=='57'):?>
            <a href="<?php echo $this->getUrl('apple-iphone-repair.html')?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>" class="product-image">
                <?php if(!$resizeImage = $this->getResizeImage()): ?>
                    <?php
                        $style = '';
                        if (!empty($width)):
                            $style = 'width: ' . (is_numeric($width) ? $width . 'px' : $width);
                        elseif (!empty($height)):
                            $style = 'height: ' . (is_numeric($height) ? $height . 'px' : $height);
                        endif;
                    ?>
                    <img src="<?php echo $this->getImage($_category) ?>" style="<?php echo $style ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
                <?php else: ?>
                    <img src="<?php echo Mage::helper('easycatalogimg/image')->resize($this->getImage($_category), $width, $height) ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" /><br/><span><?php echo $this->htmlEscape($_category->getName()) ?></span>
                <?php endif; ?>
            </a>
            <?php elseif ($_category->getId()=='867'):?>
            <a href="<?php echo $this->getUrl('apple-macbook-repair')?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>" class="product-image">
                <?php if(!$resizeImage = $this->getResizeImage()): ?>
                    <?php
                        $style = '';
                        if (!empty($width)):
                            $style = 'width: ' . (is_numeric($width) ? $width . 'px' : $width);
                        elseif (!empty($height)):
                            $style = 'height: ' . (is_numeric($height) ? $height . 'px' : $height);
                        endif;
                    ?>
                    <img src="<?php echo $this->getImage($_category) ?>" style="<?php echo $style ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
                <?php else: ?>
                    <img src="<?php echo Mage::helper('easycatalogimg/image')->resize($this->getImage($_category), $width, $height) ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" /><br/><span><?php echo $this->htmlEscape($_category->getName()) ?></span>
                <?php endif; ?>
            </a>
            <?php else :?>
            <a href="<?php echo $_category->getUrl()?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>" class="product-image">
                <?php if(!$resizeImage = $this->getResizeImage()): ?>
                    <?php
                        $style = '';
                        if (!empty($width)):
                            $style = 'width: ' . (is_numeric($width) ? $width . 'px' : $width);
                        elseif (!empty($height)):
                            $style = 'height: ' . (is_numeric($height) ? $height . 'px' : $height);
                        endif;
                    ?>
                    <img src="<?php echo $this->getImage($_category) ?>" style="<?php echo $style ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
                <?php else: ?>
                    <img src="<?php echo Mage::helper('easycatalogimg/image')->resize($this->getImage($_category), $width, $height) ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" /><br/><span><?php echo $this->htmlEscape($_category->getName()) ?></span>
                <?php endif; ?>
            </a>
              <?php endif; ?>
        <?php endif; ?>
       
    </li>

   

<?php endforeach; ?>

</ul>
</section>

<script type="text/javascript">decorateGeneric($$('ul.category-grid'), ['odd','even','first','last'])</script>
