<script type="text/javascript" src="<?php echo $this->getSkinUrl('close-div/jquery.min.js')?>"></script>

<script type="text/javascript">

 function showonlyone(thechosenone) {

     $('.newboxes').each(function(index) {

          if ($(this).attr("id") == thechosenone) {

               $(this).show(200);

          }

          else {

               $(this).hide(200);

          }

     });

}

</script>
<style>
#subcateswitcher {margin:0px; padding:0px; padding-right:20px;   float:left;}
</style>
<div class="list" style=" float:left;">

     <table width="100%" height="">

<tr>

 

<td style="vertical-align:top; float:left;">

 
<?php
$_categories=$this->getCurrentChildCategories();
if($_categories->count()):
$categorycount = 0;
$cms=0;
foreach ($_categories as $_category):
if($_category->getIsActive()):
$cur_category=Mage::getModel('catalog/category')->load($_category->getId());
$layer = Mage::getSingleton('catalog/layer');
$layer->setCurrentCategory($cur_category);
$catName = $this->getCurrentCategory()->getName();
$cms++;
?>
         <div id="subcateswitcher">

            <a id="myHeader1" href="javascript:showonlyone('newboxes<?php echo $cms;?>');" >

			

				<img src="<?php echo $this->getCurrentCategory()->getImageUrl() ?>" style="margin:0px; padding:0px; " onClick="document.getElementById('p<?php echo $cms;?>').style.display='none'"   />

				

			</a>

         </div>
<div class="newboxes" id="newboxes<?php echo $cms;?>" style="  display: none;  margin-top:0px; max-width: 1024px; width:100%; max-height:1100px; z-index:1111;"> 

  <div style="max-width:1000px; width:100%; height:100%; padding: 0px; margin:0px; ">		

<div style="width:100%; height:100%; padding: 0px; margin:0px; float:left; ">

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('selllist')->toHtml(); ?>


 </div>

</div> 



</div>

<?php
endif;
endforeach;
endif;
?>		 

		 

         

      

	    

 

 </td>



  



 </tr>

 </table>               
                    
            </div>